package com.example.geocare.Scan;

public class IrritantList {
    public static final String[] irritant = {
            "Aminophylline",
            "Theophylline",
            "Methylene chloride (Dichloromethane)",
            "Chlorofluorocarbons",
            "Diethylene glycol (except if it is present as unavoidable trace limit of 0.1% in finished product)",
            "Azelaic acid",
            "Bimatoprost",
            "Silver Nitrate",
            "N-5-Chlorobenzoxazol-2-ylacetamide",
            "2-Acetoxyethyltrimethylammonium hydroxide (acetylcholine) and its salts",
            "Deanol aceglumate (INN)",
            "Spironolactone (INN)",
            "[4-(4-Hydroxy-3-iodophenoxy)-3,5-diiodophenyl] acetic acid and its salts",
            "Methotrexate (INN)",
            "Aminocaproic acid (INN) and its salts",
            "Cinchophen (INN), its salts, derivatives and salts of these derivatives",
            "Thyropropic acid (INN) and its salts",
            "Trichloroacetic acid",
            "Aconitum napellus L. (leaves, roots and galenical preparations)",
            "Aconitine (principal alkaloid of Aconitum napellus L.) and its salts",
            "Adonis vernalis L. and its preparations",
            "Epinephrine (INN)",
            "Rauwolfia serpentina alkaloids and their salts",
            "Allyl  isothiocyanate",
            "Alloclamide (INN) and its salts",
            "Nalorphine (INN), its salts and ethers",
            "Sympathicomimetic amines acting on the central nervous system as defined in ASEAN member States (AMS) local law(s) or regulation(s)",
            "Aniline, its salts and its halogenated and sulphonated derivatives",
            "Betoxycaine (INN) and its salts",
            "Zoxazolamine (INN)",
            "Procainamide (INN), its salts and derivatives",
            "Benzidine",
            "Tuaminoheptane (INN), its isomers and salts",
            "Octodrine (INN) and its salts",
            "2-Amino-1,2-bis(4-methoxyphenyl)ethanol and its salts",
            "1,3-dimethylpentylamine and its salts",
            "4-Aminosalicylic acid and its salts",
            "Toluidines, their isomers, salts and halogenated and sulphonated derivatives",
            "Xylidines, their isomers, salts and halogenated and sulphonated derivatives",
            "lmperatorin (9-(3-methylbut-2-enyloxy) furo(3,2-g) chromen-7- one)",
            "Ammi majus and its galenical preparations)",
            "2,3-Dichloro-2-methylbutane",
            "Substances with androgenic effect",
            "Anthracene oil",
            "Antibiotics",
            "Antimony and its compounds",
            "Apocynum cannabinum L. and its preparations",
            "Apomorphine ((R)-5,6,6a,7-tetrahydro-6-methyl-4H-dibenzo [de,g]-quinoline-10,11-diol) and its salts",
            "Arsenic and its compounds",
            "Atropa belladonna L. and its preparations",
            "Atropine, its salts and derivatives",
            "Barium salts, with the exception of barium sulphide under the condition laid down in Annex III part 1 reference # 23, and the barium sulphate, lakes, salts, and pigments prepared from colouring agents listed in Annex IV",
            "Benzene",
            "Benzimidazol-2(3H)-one",
            "Benzazepines and benzodiazepines",
            "1–Dimethylaminomethyl- 1–methylpropyl benzoate (amylocaine) and   its salts",
            "2,2,6-Trimethyl-4-piperidyl benzoate (benzamine) and its salts",
            "Isocarboxazid (INN)",
            "Bendroflumethiazide (INN) and its derivatives",
            "Beryllium and its compounds",
            "Bromine, elemental",
            "Bretylium tosilate (INN)",
            "Carbromal (INN)",
            "Bromisoval (INN)",
            "Brompheniramine (INN) and its salts",
            "Benzilonium bromide (INN)",
            "Tetrylammonium bromide (INN)",
            "Brucine",
            "Tetracaine (INN) and its salts",
            "Mofebutazone (INN)",
            "Tolbutamide (INN)",
            "Carbutamide (INN)",
            "Phenylbutazone (INN)",
            "Cadmium and its compounds",
            "Cantharides, Cantharis vesicatoria",
            "(1R,2S)-Hexahydro-1,2-dimethyl-3,6-epoxyphthalic anhydride (cantharidin)",
            "Phenprobamate (INN)",
            "Nitroderivatives of carbazole",
            "Carbon disulphide",
            "Catalase",
            "Cephaeline and its salts",
            "Chenopodium ambrosioides (essential oil)",
            "2,2,2-Trichloroethane-1,1–diol",
            "Chlorine",
            "Chlorpropamide (INN)",
            "Diphenoxylate (INN) hydrochloride",
            "4-Phenylazophenylene-1,3-diamine citrate hydrochloride (Chrysoidine citrate hydrochloride)",
            "Chlorzoxazone (INN)",
            "2-Chloro-6-methylpyrimidin-4-yldimethylamine; (crimidine-ISO)",
            "Chlorprothixene (INN) and its salts",
            "Clofenamide (INN)",
            "N,N-bis (2-Chloroethyl)methylamine N-oxide and its salts",
            "Chlormethine (INN) and its salts",
            "Cyclophosphamide (INN) and its salts",
            "Mannomustine (INN) and its salts",
            "Butanilicaine (INN) and its salts",
            "Chlormezanone (INN)",
            "Triparanol (INN)",
            "2-[2-(4-Chlorophenyl)-2-phenylacetyl] indan 1,3-dione (chlorophacinone-ISO)",
            "Chlorphenoxamine (INN)",
            "Phenaglycodol (INN)",
            "Chloroethane",
            "Chromium; chromic acid and its salts",
            "Claviceps purpurea Tul., its alkaloids and galenical preparations",
            "Conium maculatum L. (fruit, powder, galenical preparations)",
            "Glycyclamide (INN)",
            "Cobalt benzenesulphonate",
            "Colchicine, its salts and derivatives",
            "Colchicoside and its derivatives",
            "Colchicum autumnale L. and its galenical preparations",
            "Convallatoxin",
            "Anamirta cocculus L. (fruit)",
            "Croton tiglium (oil)",
            "1-Butyl-3-(N-crotonoylsulphanilyl)urea",
            "Curare and curarine",
            "Synthetic curarizants",
            "Hydrogen cyanide and its salts",
            "2-alpha-Cyclohexylbenzyl(N,N,N',N'- tetraethyl)trimethylenediamine (phenetamine)",
            "Cyclomenol (INN) and its salts",
            "Sodium hexacyclonate (INN)",
            "Hexapropymate (INN)",
            "Dextropropoxyphene (INN)",
            "O,O’-Diacetyl-N-allyl-N-normorphine; Diacetylnalorphine",
            "Pipazetate (INN)  and its salts",
            "5-(alpha, beta-Dibromophenethyl)-5-methylhydantoin",
            "N,N'-Pentamethylenebis(trimethylammonium) salts, e.g. pentamethonium bromide (INN)",
            "N,N'-[(Methylimino)diethylene]bis(ethyldimethylammonium) salts, e.g. azamethonium bromide (INN)",
            "Cyclarbamate (INN)",
            "Clofenotane (INN); DDT (ISO)",
            "N,N’-Hexamethylenebis (trimethylammonium) salts, e.g. hexamethonium bromide (INN)",
            "Dichloroethanes (ethylene chlorides)",
            "Dichloroethylenes (acetylene chlorides)",
            "Lysergide (INN) and its salts",
            "2-Diethylaminoethyl 3-hydroxy-4-phenylbenzoate and its salts",
            "Cinchocaine (INN) and its salts",
            "3-Diethylaminopropyl cinnamate",
            "O,O’-Diethyl-O-4-nitrophenyl phosphorothioate (parathion-ISO)",
            "[Oxalylbis(iminoethylene)] bis[(o-chlorobenzyl) diethylammonium] salts, e.g. ambenonium chloride (INN)",
            "Methyprylon (INN) and its salts",
            "Digitaline and all heterosides of Digitalis purpurea L.",
            "7-[2-Hydroxy-3-(N-(2-hydroxyethyl)-N-methylamino)propyl] theophylline; (xanthinol)",
            "Dioxethedrin (INN) and its salts",
            "Piprocurarium iodide (INN)",
            "Propyphenazone (INN)",
            "Tetrabenazine (INN) and its salts",
            "Captodiame (INN)",
            "Mefeclorazine (INN) and its salts",
            "Dimethylamine",
            "1,1-Bis (dimethylaminomethyl)propyl benzoate (amydricaine, alypine) and its salts",
            "Methapyrilene (INN) and its salts",
            "Metamfepramone (INN) and its salts",
            "Amitriptyline (INN) and its salts",
            "Metformin (INN) and its salts",
            "Isosorbide dinitrate (INN)",
            "Malononitrile",
            "Succinonitrile",
            "Dinitrophenol isomers",
            "Inproquone (INN)",
            "Dimevamide (INN) and its salts",
            "Diphenylpyraline (INN) and its salts",
            "Sulfinpyrazone (INN)",
            "N-(3-Carbamoyl-3,3-diphenylpropyl)-N,N- diisopropylmethylammonium salts,  e.g. isopropamide iodide INN)",
            "Benactyzine (INN)",
            "Benzatropine (INN) and its salts",
            "Cyclizine (INN) and its salts",
            "5,5-Diphenyl-4-imidazolidone",
            "Probenecid (INN)",
            "Disulfiram (INN); thiram (ISO)",
            "Emetine, its salts and derivatives",
            "Ephedrine and its salts",
            "Oxanamide (INN) and its derivatives",
            "Eserine or physostigmine and its salts",
            "4-Aminobenzoic acid and its esters, with the free amino group",
            "Choline salts and their esters, e.g. choline chloride (INN)",
            "Caramiphen (INN) and its salts",
            "Diethyl 4-nitrophenyl phosphate",
            "Metethoheptazine (INN) and its salts",
            "Oxpheneridine (INN) and its salts",
            "Ethoheptazine (INN) and its salts",
            "Metheptazine (INN) and its salts",
            "Methylphenidate (INN) and its salts",
            "Doxylamine (INN) and its salts",
            "Tolboxane (INN)",
            "4-Benzyloxyphenol and 4-ethoxyphenol",
            "Parethoxycaine (INN) and its salts",
            "Fenozolone (INN)",
            "Glutethimide (INN) and its salts",
            "Ethylene oxide",
            "Bemegride (INN) and its salts",
            "Valnoctamide (INN)",
            "Haloperidol (INN)",
            "Paramethasone (INN)",
            "Fluanisone (INN)",
            "Trifluperidol (INN)",
            "Fluoresone (INN)",
            "Fluorouracil (INN)",
            "Hydrofluoric acid, its normal salts, its complexes and hydrofluorides with the exception of those given in Annex III, part 1",
            "Furfuryltrimethyl ammonium salts, e.g. furtrethonium iodide (INN)",
            "Galantamine (INN)",
            "Progestogens",
            "1,2,3,4,5,6-Hexachlorocyclohexane (BHC-ISO)",
            "1,4,4a,5,6,7,8,8a-octahydro-1,4:5,8-dimethanonaphthalene (endrin-ISO)",
            "Hexachloroethane",
            "(1R,4S,5R,8S)-1,2,3,4,10,10-Hexachloro-1,4,4a,5,8,8a-hexahydro- 1,4:5,8-dimethanonaphthalene (Isodrin-ISO)",
            "Hydrastine, hydrastinine and their salts",
            "Hydrazides and their salts",
            "Hydrazine, its derivatives and their salts",
            "Octamoxin (INN) and its salts",
            "Warfarin (INN) and its salts",
            "Ethyl bis(4-hydroxy-2-oxo-1–benzopyran-3-yl) acetate and salts of the acid",
            "Methocarbamol (INN)",
            "Propatylnitrate (INN)",
            "4,4'-Dihydroxy-3,3'-(3-methylthiopropylidene) dicoumarin",
            "Fenadiazole (INN)",
            "Nitroxoline (INN) and its salts",
            "Hyoscyamine, its salts and derivatives",
            "Hyoscyamus niger L. (leaves, seeds, powder and galenical preparations)",
            "Pemoline (INN) and its salts",
            "Iodine",
            "Decamethylenebis (trimethylammonium) salts, e.g. decamethonium bromide (INN)",
            "Ipecacuanha (Cephaelis ipecacuanha Brot. and related species) (roots,  powder and galenical preparations)",
            "(2-Isopropylpent-4-enoyl)urea (apronalide)",
            "-Santonin [(3S,5aR,9bS)-3,3a,4,5,5a,9b-hexahydro-3,5a,9- trimethylnaphto [1,2-b] furan-2,8-dione]",
            "Lobelia inflata L. and its galenical preparations",
            "Lobeline (INN) and its salts",
            "Barbiturates",
            "Mercury and its compounds except those special cases included in Annex VI",
            "3,4,5-Trimethoxyphenethylamine and its salts",
            "Metaldehyde",
            "2-(4-Allyl-2-methoxyphenoxy)-N,N-diethylacetamide and its salts",
            "Coumetarol (INN)",
            "Dextromethorphan (INN) and its salts",
            "2-Methylheptylamine (2-(N-methyl)heptylamine) and its salts",
            "Isometheptene (INN) and its salts",
            "Mecamylamine (INN)",
            "Guaifenesin (INN)",
            "Dicoumarol (INN)",
            "Phenmetrazine (INN), its derivatives and salts",
            "Thiamazole (INN)",
            "(1)  benzopyran-5-one (cyclocoumarol)",
            "Carisoprodol (INN)",
            "Meprobamate (INN)",
            "Tefazoline (INN) and its salts",
            "Arecoline",
            "Poldine metilsulfate (INN)",
            "Hydroxyzine (INN)",
            "2-Naphthol",
            "1-and 2-Naphthylamines and their salts",
            "3-(1–Naphthyl)-4-hydroxycoumarin",
            "Naphazoline (INN) and its salts",
            "Neostigmine and its salts (e.g. neostigmine bromide (INN))",
            "Nicotine and its salts",
            "Amyl nitrites",
            "Inorganic nitrites, with exception of sodium nitrite",
            "Nitrobenzene",
            "Nitrocresols and their alkali metal salts",
            "Nitrofurantoin (INN)",
            "Furazolidone (INN)",
            "Propane-1,2,3-triyl trinitrate",
            "Acenocoumarol (INN)",
            "Alkali pentacyanonitrosylferrate (2-)",
            "Nitrostilbenes, their homologues and their derivatives",
            "Noradrenaline and its salts",
            "Noscapine (INN) and its salts",
            "Guanethidine (INN) and its salts",
            "Oestrogens",
            "Oleandrin",
            "Chlortalidone (INN)",
            "Pelletierine and its salts",
            "Pentachloroethane",
            "Pentaerithrityl tetranitrate (INN)",
            "Petrichloral (INN)",
            "Octamylamine (INN) and its salts",
            "Picric acid",
            "Phenacemide (INN)",
            "Difencloxazine (INN)",
            "2-Phenylindan-1,3-dione (Phenindione)",
            "Ethylphenacemide (pheneturide) (INN)",
            "Phenprocoumon (INN)",
            "Fenyramidol (INN)",
            "Triamterene (INN) and its salts",
            "Tetraethyl pyrophosphate; TEPP-(ISO)",
            "Tritolyl phosphate",
            "Psilocybine (INN)",
            "Phosphorus and metalphosphides",
            "Thalidomide (INN) and its salts",
            "Physostigma venenosum Balf.",
            "Picrotoxin",
            "Pilocarpine and its salts",
            "alpha-Piperidin-2-ylbenzyl acetate laevorotatory threoform (Levophacetoperane) and its salts",
            "Pipradrol (INN) and its salts",
            "Azacyclonol (INN) and its salts",
            "Bietamiverine (INN)",
            "Butopiprine (INN) and its salts",
            "Lead and its compounds",
            "Coniine",
            "Prunus laurocerasus L. ('cherry laurel water')",
            "Metyrapone (INN)",
            "Radioactive substances, as defined as in ASEAN member States (AMS) local law(s) or regulation(s)",
            "Juniperus sabina L. (leaves, essential oil and galenical preparations)",
            "Hyoscine, its salts and derivatives",
            "Gold salts",
            "Selenium and its compounds with the exception of selenium disulphide under the conditions set out under reference No 49 in Annex III, Part 1",
            "Solanum nigrum L. and its galenical preparations",
            "Sparteine (INN) and its salts",
            "Glucocorticoids",
            "Datura stramonium L. and its galenical preparations",
            "Strophantines, their aglucones and their respective derivatives",
            "Strophantus species and their galenical preparations",
            "Strychnine and its salts",
            "Strychnos species and their galenical preparations",
            "Narcotics, natural and synthetic",
            "Sulphanilamide and its derivatives obtained by substitution of one or more H-atoms of the -NH2 groups, and their salts",
            "Sultiame (INN)",
            "Neodymium and its salts",
            "Thiotepa (INN)",
            "Pilocarpus jaborandi Holmes and its galenical preparations",
            "Tellurium and its compounds",
            "Xylometazoline (INN) and its salts",
            "Tetrachloroethylene",
            "Carbon tetrachloride",
            "Hexaethyl tetraphosphate",
            "Thallium and its compounds",
            "Thevetia neriifolia Juss., Glycoside extract",
            "Ethionamide (INN)",
            "Phenothiazine (INN) and its compounds",
            "Thiourea and its derivatives, with the exception of the one listed in Annex III, Part 1",
            "Mephenesin (INN) and its esters",
            "Vaccines, toxins or serums as defined in ASEAN Member States (AMS) local law(s) or regulation(s)",
            "Tranylcypromine (INN) and its salts",
            "Trichloronitromethane (chloropicrine)",
            "2,2,2-Tribromoethanol (tribromoethyl alcohol)",
            "*) not limited to the specified CAS number",
            "Tretamine (INN)",
            "Gallamine triethiodide (INN)",
            "Urginea scilla Stern. and its galenical preparations",
            "Veratrine, its salts and galenical preparations",
            "Schoenocaulon officinale Lind. (seeds and galenical preparations)",
            "Veratrum Spp. and their preparations",
            "Vinyl chloride monomer",
            "Ergocalciferol (INN) and Cholecalciferol (vitamins D2 and D3)",
            "Salts of O-alkyldithiocarbonic acids",
            "Yohimbine and its salts",
            "Dimethyl sulfoxide (INN)",
            "Diphenhydramine (INN) and its salts",
            "4-tert-Butylphenol",
            "4-tert-Butylpyrocatechol",
            "Dihydrotachysterol (INN)",
            "Dioxane",
            "Morpholine and its salts",
            "Pyrethrum album L. and its galenical preparations",
            "2-[4-Methoxybenzyl-N-(2-pyridyl)amino]ethyldimethylamine maleate",
            "Tripelennamine (INN)",
            "Tetrachlorosalicylanilides",
            "Dichlorosalicylanilides",
            "Tetrabromosalicylanilides",
            "Dibromosalicylanilides",
            "Bithionol (INN)",
            "Thiuram monosulphides",
            "Thiuram disulphides",
            "Dimethylformamide",
            "4-Phenylbut-3-en-2-one",
            "Benzoates of 4-hydroxy-3-methoxycinnamyl alcohol except for normal content in natural essences used",
            "In sun protection and in bronzing products, furocoumarines shall be below 1mg/kg",
            "Oil from the seeds of Laurus nobilis L.",
            "100 ppm in the finished cosmetic product",
            "50 ppm in products for dental and oral hygiene, and provided that Safrole is not present in toothpastes intended specifically for children.",
            "5,5'-Di-isopropyl-2,2'-dimethylbiphenyl-4,4'-diyl dihypoiodate",
            "3'-Ethyl-5',6',7’,8'-tetrahydro-5',5',8',8'-tetramethyl-2'- acetonaphthone or 7-acetyl-6-ethyl-1,1,4,4-tetramethyl-1,2,3,4- tetrahydronaphthalen",
            "o-phenylenediamine and its salts",
            "4-Methyl-m-phenylenediamine and its salts",
            "Aristolochic acid and its salts; Aristolochia spp. and their preparations",
            "Chloroform",
            "2,3,7,8,-Tetrachlorodibenzo-p-dioxin",
            "2,6-Dimethyl-1,3-dioxan-4-yl acetate (Dimethoxane)",
            "Pyrithione sodium (INNM)",
            "N-(Trichloromethylthio)-4-cyclohexene-1,2-dicarboximide (captan)",
            "2,2'-Dihydroxy-3,3',5,5',6,6'-hexachlorodiphenylmethane (hexachlorophene)",
            "6-(Piperidinyl)-2,4-pyrimidinediamine-3-oxide (minoxidil) and its salts",
            "3,4',5–Tribromosalicylanilide",
            "Phytolacca Spp. and their preparations",
            "Tretinoin (INN) (retinoic acid and its salts)",
            "and their salts",
            "1–Methoxy-2,5-diaminobenzene (2,5-Diaminoanisole) and their salts",
            "Colouring agent CI 12140",
            "Colouring agent CI 26105",
            "Colouring agent CI 42555:2",
            "Amyl 4-dimethylaminobenzoate, mixed isomers (Padimate A (INN))",
            "Entry deleted",
            "2-Amino-4-nitrophenol",
            "2-Amino-5-nitrophenol",
            "11alpha-hydroxypregn-4-ene-3,20-dione and its esters",
            "Colouring agent CI 42640",
            "Colouring agent CI 13065",
            "Colouring agent CI 42535",
            "Colouring agent CI 61554",
            "Anti-androgens of steroidal structure",
            "Zirconium and its compounds, with the exception of the substances listed under reference number 50 in Annex III, Part 1, and the zirconium lakes, pigments and salts of the colouring agents listed in Annex IV, Part 1",
            "Entry deleted",
            "Acetonitrile",
            "Tetrahydrozoline (Tetryzoline) (INN) and its salts",
            "Hydroxy-8-quinoline and its sulphate, except for the uses provided for in Annex III, Part 1 No 51",
            "Dithio-2,2'-bispyridine-dioxide-1,1' (additive with trihydrated magnesium sulphate) - (pyrithione disulphide + magnesium sulphate)",
            "Colouring agent CI 12075 and its lakes, pigments and salts",
            "Colouring agent CI 45170, Colouring agent  CI 45170:1",
            "Lidocaine (INN)",
            "1,2-Epoxybutane",
            "Colouring agent CI 15585",
            "Strontium lactate",
            "Strontium nitrate",
            "Strontium polycarboxylate",
            "Pramocaine (INN)",
            "4-Ethoxy-m-phenylenediamine and its salts",
            "2,4-Diaminophenylethanol and its salts",
            "Catechol",
            "Pyrogallol",
            "Nitrosamines",
            "Secondary alkyl- and alkanolamines and their salts",
            "4-Amino-2-nitrophenol",
            "2-Methyl-m-phenylenediamine",
            "4-tert-Butyl-3-methoxy-2,6-dinitrotoluene (Musk ambrette)",
            "Entry deleted",
            "Cells, tissues or products of human origin",
            "3,3- Bis(4-hydroxyphenyl)phthalide (Phenolphthalein) (INN)",
            "3-Imidazol-4-ylacrylic acid and its ethyl ester (Urocanic acid)",
            "Category 1 material and Category 2 material as defined in ASEAN definition of animal products.",
            "Crude and refined coal tars",
            "1,1,3,3,5,-Pentamethyl-4,6-dinitroindane (Moskene)",
            "5-tert-Butyl-1,2,3-trimethyl-4,6-dinitrobenzene (Musk tibetene)",
            "Alanroot oil (Inula helenium), when used as a fragrance ingredient.",
            "Benzyl cyanide, when used as a fragrance ingredient.",
            "Cyclamen alcohol, when used as a fragrance ingredient.",
            "Diethyl maleate, when used as a fragrance ingredient.",
            "Dihydrocoumarin, when used as a fragrance ingredient.",
            "2,4-Dihydroxy-3-methylbenzaldehyde, when used as a fragrance ingredient.",
            "3,7-Dimethyl-2-octen-1-ol (6,7-Dihydrogeraniol), when used as a fragrance ingredient.",
            "4,6-Dimethyl-8-tert-butylcoumarin, when used as a fragrance ingredient.",
            "Dimethyl citraconate, when used as a fragrance ingredient.",
            "7,11-Dimethyl-4,6,10-dodecatrien-3-one, when used as a fragrance ingredient.",
            "6,10-Dimethyl-3,5,9-undecatrien-2-one, when used as a fragrance ingredient.",
            "Diphenylamine, when used as a fragrance ingredient.",
            "Ethyl acrylate, when used as a fragrance ingredient.",
            "Fig leaf absolute (Ficus carica), when used as a fragrance ingredient.",
            "trans-2-Heptenal, when used as a fragrance ingredient.",
            "trans-2-Hexenal diethyl acetal, when used as a fragrance ingredient.",
            "trans-2-Hexenal dimethyl acetal, when used as a fragrance ingredient.",
            "Hydroabietyl alcohol, when used as a fragrance ingredient.",
            "6-Isopropyl-2-decahydronaphthalenol, when used as a fragrance ingredient.",
            "7-Methoxycoumarin, when used as a fragrance ingredient.",
            "4-(4-Methoxyphenyl)-3-butene-2-one, when used as a fragrance ingredient.",
            "1-(4-Methoxyphenyl)-1-penten-3-one, when used as a fragrance ingredient.",
            "Methyl trans-2-butenoate, when used as a fragrance ingredient.",
            "7-Methylcoumarin, when used as a fragrance ingredient.",
            "5-Methyl-2,3-hexanedione, when used as a fragrance ingredient.",
            "2-Pentylidenecyclohexanone, when used as a fragrance ingredient.",
            "3,6,10-Trimethyl-3,5,9-undecatrien-2-one, when used as a fragrance ingredient.",
            "Verbena essential oils (Lippia citriodora Kunth.) and derivatives other than absolute (CAS No 8024-12-2), when used as a fragrance ingredient.",
            "(a) 0.01 % in fine fragrance",
            "(b) 0.004 % in eau de toilette",
            "(c) 0.002 % in fragrance cream",
            "(d) 0.001 % in rinse-off products",
            "(e) 0.0002 % in other leave-on products and oral hygiene products",
            "6-(2-Chloroethyl)-6-(2-methoxyethoxy)-2,5,7,10-tetraoxa-6- silaundecane",
            "Cobalt dichloride",
            "Cobalt sulphate",
            "Nickel monoxide",
            "Dinickel trioxide",
            "Nickel dioxide",
            "Trinickel disulphide",
            "Tetracarbonylnickel",
            "Nickel sulphide",
            "Potassium bromate",
            "Carbon monoxide",
            "Buta-1,3-diene",
            "Dibenz[a,h]anthracene",
            "Benz[a]anthracene",
            "Benzo[e]pyrene",
            "Benzo[j]fluoranthene",
            "Benz[e]acephenanthrylene",
            "Benzo[k]fluoranthene",
            "Chrysene",
            "2-Bromopropane",
            "Trichloroethylene",
            "1,2-Dibromo-3-chloropropane",
            "2,3-Dibromopropan-1-ol",
            "1,3-Dichloropropan-2-ol",
            "α, α, α -Trichlorotoluene",
            "α -Chlorotoluene",
            "1,2-Dibromoethane",
            "Hexachlorobenzene",
            "Bromoethylene",
            "1,4-Dichlorobut-2-ene",
            "Methyloxirane",
            "(Epoxyethyl)benzene",
            "1-Chloro-2,3-epoxypropane",
            "R-1-Chloro-2,3-epoxypropane",
            "1,2-Epoxy-3-phenoxypropane",
            "2,3-Epoxypropan-1-ol",
            "R-2,3-Epoxy-1-propanol",
            "2,2'-Bioxirane",
            "(2RS,3RS)-3-(2-Chlorophenyl)-2-(4-fluorophenyl)-[1H-1,2,4- triazol-1-yl)methyl]oxirane; epoxiconazole",
            "Chloromethyl methyl ether",
            "[Ethylene glycol monomethyl ether (EGMME)]",
            "[Ethylene glycol monoethyl ether (EGMEE)",
            "Oxybis[chloromethane]; bis (Chloromethyl) ether",
            "2-Methoxypropanol",
            "Propiolactone",
            "Dimethylcarbamoyl chloride",
            "Urethane",
            "2-Methoxyethyl acetate",
            "2-Ethoxyethyl acetate",
            "Methoxyacetic acid",
            "Dibutyl phthalate",
            "bis(2-Methyoxyethyl) ether",
            "bis(2-Ethylhexyl) phthalate",
            "bis(2-Methoxyethyl) phthalate",
            "2-Methoxypropyl acetate",
            "2-Ethylhexyl[[[3,5-bis(1,1-dimethylethyl)-4-hydroxyphenyl]- methyl]thio] acetate",
            "Acrylamide, unless regulated elsewhere in this Directive",
            "Acrylonitrile",
            "2-Nitropropane",
            "Dinoseb, its salts and esters with the exception of those specified elsewhere in this list",
            "2-Nitroanisole",
            "4-Nitrobiphenyl",
            "Dinitrotoluene, technical grade",
            "Binapacryl",
            "2-Nitronaphthalene",
            "2,3-Dinitrotoluene",
            "5-Nitroacenaphthene",
            "2,6-Dinitrotoluene",
            "3,4-Dinitrotoluene",
            "3,5-Dinitrotoluene",
            "2,5-Dinitrotoluene",
            "Dinoterb, its salts and esters",
            "Nitrofen",
            "Dinitrotoluene",
            "Diazomethane",
            "1,4,5,8-Tetraaminoanthraquinone (Disperse Blue 1)",
            "Dimethylnitrosoamine",
            "1-Methyl-3-nitro-1-nitrosoguanidine",
            "Nitrosodipropylamine",
            "2,2’-(Nitrosoimino)bisethanol",
            "4,4'-Methylenedianiline",
            "4,4'-(4-Iminocyclohexa-2,5-dienylidenemethylene) dianiline hydrochloride",
            "4,4'-Methylenedi-o-toluidine",
            "o-Anisidine",
            "3,3'-Dimethoxybenzidine",
            "Salts of o-dianisidine",
            "o-Dianisidine based azo dyes",
            "3,3'-Dichlorobenzidine",
            "Benzidine dihydrochloride",
            "[[1,1'-Biphenyl]-4,4'-diyl]diammonium sulphate",
            "3,3'-Dichlorobenzidine dihydrochloride",
            "Benzidine sulphate",
            "Benzidine acetate",
            "3,3'-Dichlorobenzidine dihydrogen bis(sulphate)",
            "3,3'-Dichlorobenzidine sulphate",
            "Benzidine based azo dyes",
            "4,4'-Bi-o-toluidine",
            "4,4'-Bi-o-toluidine dihydrochloride",
            "[3,3'-Dimethyl[1,1'-biphenyl]-4,4'-diyl]diammonium bis(hydrogen sulphate)",
            "4,4'-Bi-o-toluidine sulphate",
            "o-Toluidine based dyes",
            "Biphenyl-4-ylamine and its salts",
            "Azobenzene",
            "(Methyl-ONN-azoxy)methyl acetate",
            "Cycloheximide",
            "2-Methylaziridine (propyleneimine)",
            "Imidazolidine-2-thione",
            "Furan",
            "Aziridine",
            "Captafol",
            "Carbadox",
            "Flumioxazin",
            "Tridemorph",
            "Vinclozolin",
            "Fluazifop-butyl",
            "Flusilazole",
            "1,3,5-Tris(oxiranylmethyl)-1,3,5-triazine-2,4,6(1H,3H,5H)-trione",
            "Thioacetamide",
            "N,N-Dimethylformamide",
            "Formamide",
            "N-Methylacetamide",
            "N-Methylformamide",
            "N,N-Dimethylacetamide",
            "Hexamethylphosphoric-triamide",
            "Diethyl sulphate",
            "Dimethyl sulphate",
            "1,3-Propanesultone",
            "Dimethylsulphamoyl-chloride",
            "Sulfallate",
            "Distillates (petroleum), light catalytic cracked",
            "Distillates (petroleum), intermediate catalytic cracked",
            "Distillates (petroleum), light thermal cracked",
            "Distillates (petroleum), hydrodesulfurised light catalytic cracked",
            "Distillates (petroleum), light steam-cracked naphtha",
            "Distillates (petroleum), cracked steam-cracked petroleum distillates",
            "Gas oils (petroleum), steam-cracked",
            "Distillates (petroleum), hydrodesulfurised thermal cracked middle",
            "Gas oils (petroleum), thermal-cracked, hydrodesulfurised",
            "Residues (petroleum), hydrogenated steam-cracked naphtha",
            "Residues (petroleum), steam-cracked naphtha distn.",
            "Distillates (petroleum), light catalytic cracked, thermally degraded",
            "Residues (petroleum), steam-cracked heat-soaked naphtha",
            "Gas oils (petroleum), light vacuum, thermal-cracked hydrodesulfurised",
            "Distillates (petroleum), hydrodesulfurised middle coker",
            "Distillates (petroleum), heavy steam-cracked",
            "Residues (petroleum), atm. Tower",
            "Gas oils (petroleum), heavy vacuum",
            "Distillates (petroleum), heavy catalytic cracked",
            "Clarified oils (petroleum), catalytic cracked",
            "Residues (petroleum), catalytic reformer fractionator",
            "Residues (petroleum), hydrocracked",
            "Residues (petroleum), thermal cracked",
            "Distillates (petroleum), heavy thermal cracked",
            "Gas oils (petroleum), hydrotreated vacuum",
            "Residues (petroleum), hydrodesulfurised atmospheric tower",
            "Gas oils (petroleum), hydrodesulfurised heavy vacuum",
            "Residues (petroleum), steam-cracked",
            "Residues (petroleum), atmospheric",
            "Clarified oils (petroleum), hydrodesulfurised catalytic cracked",
            "Distillates (petroleum), hydrodesulfurised intermediate catalytic cracked",
            "Distillates (petroleum), hydrodesulfurised heavy catalytic cracked",
            "Fuel oil, residues-straight-run gas oils, high-sulphur",
            "Fuel oil, residual",
            "Residues (petroleum), catalytic reformer fractionator residue distn.",
            "Residues (petroleum), heavy coker gas oil and vacuum gas oil",
            "Residues (petroleum), heavy coker and light vacuum",
            "Residues (petroleum), light vacuum",
            "Residues (petroleum), steam-cracked light",
            "Fuel oil, No 6",
            "Residues (petroleum), topping plant, low-sulphur",
            "Gas oils (petroleum), heavy atmospheric",
            "Residues (petroleum), coker scrubber, condensed-ring-arom.- contg",
            "Distillates (petroleum), petroleum residues vacuum",
            "Residues (petroleum), steam-cracked, resinous",
            "Distillates (petroleum), intermediate vacuum",
            "Distillates (petroleum), light vacuum",
            "Distillates (petroleum), vacuum",
            "Gas oils (petroleum), hydrodesulfurised coker heavy vacuum",
            "Residues (petroleum), steam-cracked, distillates",
            "Residues (petroleum), vacuum, light",
            "Fuel oil, heavy, high-sulphur",
            "Residues (petroleum), catalytic cracking",
            "Distillates (petroleum), intermediate catalytic cracked, thermally degraded",
            "Residual oils (petroleum)",
            "Residues, steam cracked, thermally treated",
            "Distillates (petroleum), hydrodesulfurised full-range middle",
            "Distillates (petroleum), light paraffinic",
            "Distillates (petroleum), heavy paraffinic",
            "Distillates (petroleum), light naphthenic",
            "Distillates (petroleum), heavy naphthenic",
            "Distillates (petroleum), acid-treated heavy naphthenic",
            "Distillates (petroleum), acid-treated light naphthenic",
            "Distillates (petroleum), acid-treated heavy paraffinic",
            "Distillates (petroleum), acid-treated light paraffinic",
            "Distillates (petroleum), chemically neutralised heavy paraffinic",
            "Distillates (petroleum), chemically neutralised light paraffinic",
            "Distillates (petroleum), chemically neutralised heavy naphthenic",
            "Distillates (petroleum), chemically neutralised light naphthenic",
            "Extracts (petroleum), light naphthenic distillate solvent",
            "Extracts (petroleum), heavy paraffinic distillate solvent",
            "Extracts (petroleum), light paraffinic distillate solvent",
            "Extracts (petroleum), heavy naphthenic distillate solvent",
            "Extracts (petroleum), light vacuum gas oil solvent",
            "Hydrocarbons, C26-55, arom.-rich",
            "Disodium 3,3'-[[1,1'-biphenyl]-4,4'-diylbis(azo)] bis(4- aminonaphthalene-1- sulphonate)",
            "Disodium 4-amino-3-[[4'-[(2,4-diaminophenyl)azo] [1,1'- biphenyl]-4-yl] azo]-5-hydroxy-6-(phenylazo)naphthalene-2,7- disulphonate",
            "Tetrasodium 3,3'-[[1,1'-biphenyl]-4,4'-diylbis(azo)]bis[5-amino-4- hydroxynaphthalene-2,7-disulphonate]",
            "4-o-Tolylazo-o-toluidine",
            "4-Aminoazobenzene",
            "Disodium[5-[[4'-[[2,6-dihydroxy-3-[(2-hydroxy-5- sulphophenyl)azo]phenyl]azo][1,1'-biphenyl]-4- yl]azo]salicylato(4-)]cuprate(2-)",
            "Resorcinol diglycidyl ether",
            "1,3-Diphenylguanidine",
            "Heptachlor-epoxide",
            "4-Nitrosophenol",
            "Carbendazim",
            "Allyl glycidyl ether",
            "Chloroacetaldehyde",
            "Hexane",
            "2-(2-Methoxyethoxy)ethanol",
            "(+/–)-2-(2,4-Dichlorophenyl)-3-(1H-1,2,4-triazol-1-yl)propyl- 1,1,2,2-tetrafluoroethylether",
            "4-[4-(1,3-Dihydroxyprop-2-yl)phenylamino]-1,8-dihydroxy-5- nitroanthraquinone",
            "5,6,12,13-Tetrachloroanthra(2,1,9-def:6,5,10- d’e’f’)diisoquinoline-1,3,8,10 (2H,9H)-tetrone",
            "Tris(2-Chloroethyl) phosphate",
            "4'-Ethoxy-2-benzimidazoleanilide",
            "Nickel dihydroxide",
            "N,N-Dimethylaniline",
            "Simazine",
            "Bis(cyclopentadienyl)-bis(2,6-difluoro-3-(pyrrol-1-yl)- phenyl)titanium",
            "N,N,N',N'-Tetraglycidyl-4,4'-diamino-3,3'-diethyldiphenylmethane",
            "Divanadium pentaoxide",
            "Alkali salts of pentachlorophenol",
            "Phosphamidon",
            "N-(Trichloromethylthio)phthalimide",
            "N-2-Naphthylaniline",
            "Ziram",
            "1-Bromo-3,4,5-trifluorobenzene",
            "Propazine",
            "3-(4-Chlorophenyl)-1,1-dimethyluronium trichloroacetate; monuron-TCA",
            "Isoxaflutole",
            "Kresoxim-methyl",
            "Chlordecone",
            "9-Vinylcarbazole",
            "2-Ethylhexanoic acid",
            "Monuron",
            "Morpholine-4-carbonyl chloride",
            "Daminozide",
            "Alachlor",
            "UVCB condensation product of: tetrakis- hydroxymethylphosphonium chloride, urea and distilled hydrogenated C16-18 tallow alkylamine",
            "Ioxynil",
            "3,5-Dibromo-4-hydroxybenzonitrile",
            "2,6-Dibromo-4-cyanophenyl octanoate",
            "[4-[[4-(Dimethylamino)phenyl][4-[ethyl(3- sulphonatobenyl)amino]phenyl]methylene]cyclohexa-2,5-dien- 1-ylidene](ethyl)(3-sulphonatobenzyl)ammonium, sodium salt",
            "5-Chloro-1,3-dihydro-2H-indol-2-one",
            "Benomyl",
            "Chlorothalonil",
            "N'-(4-Chloro-o-tolyl)-N,N-dimethylformamidine monohydrochloride",
            "4,4'-Methylenebis(2-ethylaniline)",
            "Valinamide",
            "[(p-Tolyloxy)methyl]oxirane",
            "[(m-Tolyloxy)methyl]oxirane",
            "2,3-Epoxypropyl o-tolyl ether",
            "[(Tolyloxy)methyl]oxirane, cresyl glycidyl ether",
            "Di-allate",
            "Benzyl 2,4-dibromobutanoate",
            "Trifluoroiodomethane",
            "Thiophanate-methyl",
            "Dodecachloropentacyclo[5.2.1.02,6.03,9.05,8]decane",
            "Propyzamide",
            "Butyl glycidyl ether",
            "2,3,4-Trichlorobut-1-ene",
            "Chinomethionate",
            "(R)-α-Phenylethylammonium (-)-(1R,2S)-(1,2- epoxypropyl)phosphonate monohydrate",
            "5-Ethoxy-3-trichloromethyl-1,2,4-thiadiazole",
            "Disperse Yellow 3",
            "1,2,4-Triazole",
            "Aldrin",
            "Diuron",
            "Linuron",
            "Nickel carbonate",
            "3-(4-Isopropylphenyl)-1,1-dimethylurea",
            "Iprodione",
            "4-Cyano-2,6-diiodophenyl octanoate",
            "5-(2,4-Dioxo-1,2,3,4-tetrahydropyrimidine)-3-fluoro-2- hydroxymethyltetrahydrofuran",
            "Crotonaldehyde",
            "Hexahydrocyclopenta(c)pyrrole-1-(1H)-ammonium N- ethoxycarbonyl-N-(p-tolylsulfonyl)azanide",
            "4,4'-Carbonimidoylbis[N,N-dimethylaniline] and its salts",
            "DNOC",
            "Toluidinium chloride",
            "Toluidine sulphate (1:1)",
            "2-(4-tert-Butylphenyl)ethanol",
            "Fenthion",
            "Chlordane, pur",
            "Hexan-2-one",
            "Fenarimol",
            "Acetamide",
            "N-cyclohexyl-N-methoxy-2,5-dimethyl-3-furamide",
            "Dieldrin",
            "4,4'- Isobutylethylidenediphenol",
            "Chlordimeform",
            "Amitrole",
            "Carbaryl",
            "Distillates (petroleum), light hydrocracked",
            "1-Ethyl-1-methylmorpholinium bromide",
            "(3-Chlorophenyl)-(4-methoxy-3-nitrophenyl)methanone",
            "Fuels, diesel, except if the full refining history is known and it can be shown that the substance from which it is produced is not a carcinogen",
            "Fuel oil, no. 2",
            "Fuel oil, no. 4",
            "Fuels, diesel, no. 2",
            "2,2-Dibromo-2-nitroethanol",
            "1-Ethyl-1-methylpyrrolidinium bromide",
            "Monocrotophos",
            "Nickel",
            "Bromomethane",
            "Chloromethane",
            "Iodomethane",
            "Bromoethane",
            "Heptachlor",
            "Fentin hydroxide",
            "Nickel sulphate",
            "3,5,5-Trimethylcyclohex-2-enone",
            "2,3-Dichloropropene",
            "Fluazifop-P-butyl",
            "(S)-2,3-Dihydro-1H-indole-carboxylic acid",
            "Toxaphene",
            "(4-Hydrazinophenyl)-N-methylmethanesulfonamide hydrochloride",
            "CI Solvent Yellow 14",
            "Chlozolinate",
            "Alkanes, C10-13, chloro",
            "Pentachlorophenol",
            "2,4,6-Trichlorophenol",
            "Diethylcarbamoyl-chloride",
            "1-Vinyl-2-pyrrolidone",
            "Myclobutanil; 2-(4-chlorophenyl)-2-(1H-1,2,4-triazol-1- ylmethyl)hexanenitrile",
            "Fentin acetate",
            "Biphenyl-2-ylamine",
            "trans-4-Cyclohexyl-L-proline monohydrochloride",
            "2-Methyl-m-phenylene diisocyanate",
            "4-Methyl-m-phenylene diisocyanate",
            "m-Tolylidene diisocyanate",
            "Fuels, jet aircraft, coal solvent extn., hydrocracked hydrogenated",
            "Fuels, diesel, coal solvent extn., hydrocracked hydrogenated",
            "Pitch, if it contains > 0.005 % w/w benzo[a]pyrene",
            "2-Butanone oxime",
            "Hydrocarbons, C16-20, solvent-dewaxed hydrocracked paraffinic distn. residue",
            "alpha, alpha -Dichlorotoluene",
            "Mineral wool, with the exception of those specified elsewhere in this Annex; [Man-made vitreous (silicate) fibres with random orientation with alkaline oxide and alkali earth oxide (Na2O + K2O + CaO + MgO + BaO) content greater than 18 % by weight] .",
            "Reaction product of acetophenone, formaldehyde, cyclohexylamine, methanol and acetic acid",
            "Moved or Deleted (See Ref. No. 1067)",
            "Moved or Deleted (See Ref. No. 195)",
            "Trisodium bis(7-acetamido-2-(4-nitro-2-oxidophenylazo)-3- sulfonato-1-naphtholato)chromate(1-)",
            "A mixture of: 4-allyl-2,6-bis(2,3-epoxypropyl)phenol;4-allyl-6-[3- [6-[3-[6-[3-(4-allyl-2,6-bis(2,3-epoxypropyl)phenoxy)-2- hydroxypropyl]-4-allyl-2-(2,3-epoxypropyl)phenoxy]-2- hydroxypropyl]-4-allyl-2-(2,3-epoxypropyl)phenoxy]-2- hydroxypropyl]-2-(2,3-epoxypropyl)phenol;4-allyl-6-[3-(4-allyl- 2,6-bis(2,3-epoxypropyl)phenoxy)-2-hydroxypropyl]-2-(2,3- epoxypropyl)phenol;4-allyl-6-[3-[6-[3-(4-allyl-2,6-bis(2,3- epoxypropyl)phenoxy)-2-hydroxypropyl]-4-allyl-2-(2,3- epoxypropyl)phenoxy]-2-hydroxypropyl]-2-(2,3- epoxypropyl)phenol",
            "Costus root oil (Saussurea lappa Clarke), when used as a fragrance ingredient",
            "7-Ethoxy-4-methylcoumarin, when used as a fragrance ingredient",
            "Hexahydrocoumarin, when used as a fragrance ingredient",
            "Exudation of Myroxylon pereirae (Royle) Klotzch (Peru Balsam, crude) when used as a fragrance ingredient",
            "Isobutyl nitrite",
            "Isoprene (stabilised); (2-Methyl-1,3-butadiene)",
            "1-Bromopropane; n-Propyl bromide",
            "Chloroprene (stabilised); (2-Chlorobuta-1,3-diene)",
            "1,2,3-Trichloropropane",
            "Ethylene glycol dimethyl ether (EGDME)",
            "Dinocap (ISO)",
            "Diaminotoluene, technical product -mixture of [4-methyl-m- phenylene diamine](2) and [2-methyl-m-phenylene diamine](3)  - methyl-phenylenediamine(1)",
            "p-Chlorobenzotrichloride",
            "Diphenylether; Octabromo derivate",
            "1,2-bis(2-methoxyethoxy)ethane; Triethylene glycol dimethyl ether; (TEGDME);",
            "Tetrahydrothiopyran-3-carboxaldehyde",
            "4,4'-Bis(dimethylamino)benzophenone; (Michler's ketone)",
            "Oxiranemethanol, 4-methylbenzene-sulfonate, (S)-",
            "n-Pentyl-isopentylphthalate [2]; di-n-Pentyl phthalate [3];",
            "Diisopentylphthalate [4]",
            "Benzyl butyl phthalate (BBP)",
            "1,2-Benzenedicarboxylic acid, di-C7-11- branched and linear alkyl esters",
            "A mixture of: Disodium 4-(3-ethoxycarbonyl-4-(5-(3- ethoxycarbonyl-5-hydroxy-1-(4-sulfonatophenyl)pyrazol-4- yl)penta-2,4-dienylidene)-4,5-dihydro-5-oxopyrazol-1- yl)benzenesulfonate,and trisodium 4-(3-ethoxycarbonyl-4-(5-(3- ethoxycarbonyl-5-oxido-1-(4-sulfonatophenyl)pyrazol-4-yl) penta-2,4-dienylidene)-4,5-dihydro-5-oxopyrazol-1- yl)benzenesulfonate",
            "(Methylenebis(4,1-phenylenazo(1-(3-(dimethylamino)propyl)-1,2- dihydro-6-hydroxy-4-methyl-2-oxopyridine-5,3diyl)))-1,1'- dipyridinium dichloride dihydrochloride",
            "2-[2-Hydroxy-3-(2-chlorophenyl)carbamoyl-1-naphthylazo]-7-[2- hydroxy-3-(3-methylphenyl)carbamoyl-1-naphthylazo]fluoren-9- one",
            "Azafenidin",
            "2,4,5-Trimethylaniline [1]; 2,4,5-trimethylaniline hydrochloride [2]",
            "4,4'-Thiodianiline and its salts",
            "4,4'-Oxydianiline (p-aminophenyl ether) and its salts",
            "N,N,N',N'-Tetramethyl-4,4'-methylendianiline",
            "6-Methoxy-m-toluidine; (p-Cresidine)",
            "3-Ethyl-2-methyl-2-(3-methylbutyl)-1,3-oxazolidine",
            "A mixture of: 1,3,5-Tris(3-Aminomethylphenyl)-1,3,5-(1H,3H,5H)- triazine-2,4,6-trione, and a mixture of oligomers of 3,5-bis(3- Aminomethylphenyl)-1-poly[3,5-bis(3-aminomethylphenyl)-2,4,6- trioxo-1,3,5-(1H,3H,5H)-triazin-1-yl]-1,3,5-(1H,3H,5H)-triazine- 2,4,6-trione",
            "2-Nitrotoluene",
            "Tributyl phosphate",
            "Naphthalene",
            "Nonylphenol; 4-Nonylphenol, branched",
            "1,1,2-trichloroethane",
            "Pentachloroethane",
            "Vinylidene chloride (1,1-Dichloroethylene)",
            "Allyl chloride (3-Chloropropene)",
            "1,4-Dichlorobenzene (p-Dichlorobenzene)",
            "Bis(2-chloroethyl) ether",
            "Phenol",
            "Bisphenol A (4,4'-Isopropylidenediphenol)",
            "Trioxymethylene (1,3,5-Trioxan)",
            "Propargite (ISO)",
            "1-Chloro-4-nitrobenzene",
            "Molinate (ISO)",
            "Fenpropimorph",
            "Entry deleted",
            "Methyl isocyanate",
            "N,N-Dimethylanilinium tetrakis(pentafluorophenyl)borate",
            "O,O'-(Ethenylmethylsilylene)di[(4-methylpentan-2-one)oxime]",
            "A 2:1 mixture of: 4-(7-Hydroxy-2,4,4-trimethyl-2- chromanyl)resorcinol-4-yl-tris(6-diazo-5,6-dihydro-5- oxonaphthalene-1-sulfonate), and 4-(7-hydroxy-2,4,4-trimethyl- 2-chromanyl)resorcinolbis(6-diazo-5,6-dihydro-5- oxonaphthalene-1-sulfonate)",
            "diazo-5,6-dihydro-5-oxo-naphthalenesulfonate (1:3)",
            "Malachite green hydrochloride [1] Malachite green oxalate [2]",
            "1-(4-Chlorophenyl)-4,4-dimethyl-3-(1,2,4-triazol-1-ylmethyl) pentan-3-ol",
            "5-(3-Butyryl-2,4,6-trimethylphenyl)-2-[1-(ethoxyimino)propyl]-3- hydroxycyclohex-2-en-1-one",
            "trans-4-Phenyl-L-proline",
            "Bromoxynil heptanoate (ISO)",
            "A mixture of: 5-[(4-[(7-Amino-1-hydroxy-3-sulfo-2-naphthyl)azo]- 2,5-diethoxyphenyl)azo]-2-[(3-phosphonophenyl)azo]benzoic acid, and 5-[(4-[(7-amino-1-hydroxy-3-sulfo-2-naphthyl)azo]-2,5- diethoxyphenyl)azo]-3-[(3-phosphonophenyl)azo]benzoic acid",
            "2-{4-(2-Ammoniopropylamino)-6-[4-hydroxy-3-(5-methyl-2- methoxy-4-sulfamoylphenylazo)-2-sulfonatonaphth-7ylamino]- 1,3,5-triazin-2-ylamino}-2-aminopropyl formate",
            "5-Nitro-o-toluidine [1] 5-Nitro-o-toluidine hydrochloride [2]",
            "1-(1-Naphthylmethyl)quinolinium chloride",
            "(R)-5-Bromo-3-(1-methyl-2-pyrrolidinylmethyl)-1H-indole",
            "Pymetrozine (ISO)",
            "Oxadiargyl (ISO)",
            "Chlorotoluron; (3-(3-Chloro-p-tolyl)-1,1-dimethylurea)",
            "N-[2-(3-Acetyl-5-nitrothiophen-2-ylazo)-5-diethylaminophenyl] acetamide",
            "1,3-Bis(vinylsulfonylacetamido)propane",
            "p-Phenetidine; (4-Ethoxyaniline)",
            "m-Phenylenediamine and its salts",
            "Residues (coal tar), creosote oil distn., if it contains > 0.005 % w/w benzo[a]pyrene",
            "Creosote oil, if it contains > 0.005 %w/w benzo[a]pyrene",
            "Creosote, if it contains > 0.005 % w/w benzo[a]pyrene",
            "Extract residues (coal), creosote oil acid, wash oil extract residue",
            "6-Methoxy-2,3-pyridinediamine and its HCl salt, when used as a substance in hair dye products",
            "2,3-Naphthalenediol, when used as a substance in hair dye products",
            "2,4-Diaminodiphenylamine, when used as a substance in hair dye products",
            "2,6-Bis(2-hydroxyethoxy)-3,5-pyridinediamine and its HCl salt, when used as a substance in hair dye products",
            "2-Methoxymethyl-p-aminophenol and its HCl salt, when used as a substance in hair dye products",
            "4,5-Diamino-1-methylpyrazole and its HCl salt, when used as a substance in hair dye products",
            "4,5-Diamino-1-((4-chlorophenyl)methyl)-1H-pyrazole sulfate, when used as a substance in hair dye products",
            "4-Chloro-2-aminophenol, when used as a substance in hair dye products",
            "4-Hydroxyindole, when used as a substance in hair dye products",
            "4-Methoxytoluene-2,5-diamine and its HCl salt, when used as a substance in hair dye products",
            "5-Amino-4-fluoro-2-methylphenol sulfate, when used as a substance in hair dye products",
            "N,N-Diethyl-m-aminophenol, when used as a substance in hair dye products",
            "N,N-Dimethyl-2,6-pyridinediamine and its HCl salt, when used as a substance in hair dye products",
            "N-Cyclopentyl-m-aminophenol, when used as a substance in hair dye products",
            "N-(2-Methoxyethyl)-p-phenylenediamine and its HCl salt, when used as a substance in hair dye products",
            "2,4-Diamino-5-methylphenetol and its HCl salt, when used as a substance in hair dye products",
            "1,7-Naphthalenediol, when used as a substance in hair dye products",
            "3,4-Diaminobenzoic acid, when used as a substance in hair dye products",
            "2-Aminomethyl-p-aminophenol and its HCl salt, when used as a substance in hair dye products",
            "Solvent Red 1 (CI 12150), when used as a substance in hair dye products",
            "Acid Orange 24 (CI 20170), when used as a substance in hair dye products",
            "Acid Red 73 (CI 27290), when used as a substance in hair dye products",
            "PEG-3,2',2'-di-p-phenylenediamine",
            "6-Nitro-o-toluidine",
            "HC Yellow No 11",
            "HC Orange No 3",
            "HC Green No 1",
            "HC Red No 8 and its salts",
            "Tetrahydro-6-nitroquinoxaline and its salts",
            "Disperse Red 15, except as impurity in Disperse Violet 1",
            "4-Amino-3-fluorophenol",
            "N,N'-Dihexadecyl-N,N'-bis(2-hydroxyethyl)propanediamide; Bishydroxyethyl Biscetyl Malonamide",
            "1-Methyl-2,4,5-trihydroxybenzene and its salts, when used as a substance in hair dye products",
            "2,6-Dihydroxy-4-methylpyridine and its salts, when used as a substance in hair dye products",
            "5-Hydroxy-1,4-benzodioxane and its salts, when used as a substance in hair dye products",
            "3,4-Methylenedioxyphenol and its salts, when used as a substance in hair dye products",
            "3,4-Methylenedioxyaniline and its salts, when used as a substance in hair dye products",
            "Hydroxypyridinone and its salts, when used as a substance in hair dye products",
            "3-Nitro-4-aminophenoxyethanol and its salts, when used as a substance in hair dye products",
            "2-Methoxy-4-nitrophenol (4-Nitroguaiacol) and its salts, when used as a substance in hair dye products",
            "CI Acid Black 131 and its salts, when used as a substance in hair dye products",
            "1,3,5-Trihydroxybenzene (Phloroglucinol) and its salts, when used as a substance in hair dye products",
            "1,2,4-Benzenetriacetate and its salts, when used as a substance in hair dye products",
            "Ethanol, 2,2’-iminobis-, reaction products with epichlorohydrin and 2-nitro-1,4-benzenediamine (HC Blue No. 5) and its salts, when used as a substance in hair dye products",
            "N-Methyl-1,4-diaminoanthraquinone, reaction products with epichlorohydrin and monoethanolamine (HC Blue No. 4) and its salts, when used as a substance in hair dye products",
            "4-Aminobenzenesulfonic acid and its salts, when used as a substance in hair dye products",
            "3,3’-(Sulfonylbis(2-nitro-4,1-phenylene)imino)bis(6- (phenylamino)) benzenesulfonic acid and its salts, when used as a substance in hair dye products",
            "3(or 5)-((4-(Benzylmethylamino)phenyl)azo)-1,2-(or 1,4)- dimethyl-1H-1,2,4-triazolium and its salts, when used as a substance in hair dye products",
            "2,2’-((3-Chloro-4-((2,6-dichloro-4- nitrophenyl)azo)phenyl)imino)bisethanol(Disperse Brown 1) and its salts, when used as a substance in hair dye products",
            "Benzothiazolium, 2-[[4-[ethyl(2-hydroxyethyl)amino]phenyl]azo]- 6-methoxy-3-methyl- and its salts, when used as a substance in hair dye products",
            "2-[(4-Chloro-2-nitrophenyl)azo]-N-(2-methoxyphenyl)-3- oxobutanamide (Pigment Yellow 73) and its salts, when used as a substance in hair dye products",
            "2,2’-[(3,3’-dichloro[1,1’biphenyl]-4,4’-diyl)bis(azo)]bis[3-oxo-N- phenylbutanamide] (Pigment Yellow 12) and its salts, when used as a substance in hair dye products",
            "2,2’(1,2-Ethenediyl)bis[5-((4-ethoxyphenyl)azo]benzenesulfonic acid) and its salts, when used as a substance in hair dye products",
            "2,3-Dihydro-2,2-dimethyl-6-[(4-(phenylazo)-1-naphthelenyl)azo]- 1H-pyrimidine (Solvent Black 3) and its salts, when used as a substance in hair dye products",
            "3(or5)-[[4-[(7-amino-1-hydroxy-3-sulphonato-2-naphthyl)azo]-1- naphthyl]azo]salicylic acid and its salts, when used as a substance in hair dye products",
            "2-Naphthalenesulfonic acid, 7-(benzoylamino)-4-hydroxy-3-[[4- [(4-sulfophenyl)azo]phenyl]azo]- and its salts, when used as a substance in hair dye products",
            "(micro-((7,7'-Iminobis(4-hydroxy-3-((2-hydroxy-5-(N- methylsulphamoyl)phenyl)azo)naphthalene-2- sulphonato))(6-)))dicuprate and its salts, when used as a substance in hair dye products",
            "3-[(4-(Acetylamino)phenyl)azo]-4-hydroxy-7-[[[[5-hydroxy-6- (phenylazo)-7-sulfo-2-naphthalenyl] amino]carbonyl]amino]-2- naphthalenesulfonic acid and its salts, when used as a substance in hair dye products",
            "2-Naphthalenesulfonic acid, 7,7'-(carbonyldiimino)bis(4- hydroxy-3-[[2-sulfo-4-[(4-sulfophenyl)azo] phenyl]azo]- and its salts, when used as a substance in hair dye products",
            "Ethanaminium, N-(4-[bis[4-(diethylamino)phenyl]methylene]-2,5- cyclohexadien-1-ylidene)-N-ethyl- and its salts, when used as a substance in hair dye products",
            "3H-Indolium, 2-[[(4-methoxyphenyl)methylhydrazono]methyl]- 1,3,3-trimethyl- and its salts, when used as a substance in hair dye products",
            "3H-Indolium, 2-(2-((2,4-dimethoxyphenyl)amino)ethenyl)-1,3,3- trimethyl- and its salts, when used as a substance in hair dye products",
            "Nigrosine spirit soluble (Solvent Black 5), when used as a substance in hair dye products",
            "Phenoxazin-5-ium, 3,7-bis(diethylamino)-, and its salts, when used as a substance in hair dye products",
            "Benzo[a]phenoxazin-7-ium, 9-(dimethylamino)-, and its salts, when used as a substance in hair dye products",
            "6-Amino-2-(2,4-dimethylphenyl)-1H-benz[de]isoquinoline- 1,3(2H)-dione (Solvent Yellow 44) and its salts, when used as a substance in hair dye products",
            "[(dimethylamino)methyl]phenyl]amino]anthraquinone and its salts, when used as a substance in hair dye products",
            "Laccaic Acid (CI Natural Red 25) and its salts, when used as a substance in hair dye products",
            "Benzenesulfonic acid, 5-[(2,4-dinitrophenyl)amino]-2- (phenylamino)-, and its salts, when used as a substance in hair dye products",
            "4-[(4-Nitrophenyl)azo]aniline (Disperse Orange 3) and its salts, when used as a substance in hair dye products",
            "4-Nitro-m-phenylenediamine and its salts, when used as a substance in hair dye products",
            "1-Amino-4-(methylamino)-9,10-anthracenedione  (Disperse Violet 4) and its salts, when used as a substance in hair dye products",
            "N-Methyl-3-nitro-p-phenylenediamine and its salts, when used as a substance in hair dye products",
            "5) and its salts, when used as a substance in hair dye products",
            "N1-(Tris(hydroxymethyl))methyl-4-nitro-1,2-phenylenediamine (HC Yellow No 3) and its salts, when used as a substance in hair dye products",
            "2-Nitro-N-hydroxyethyl-p-anisidine and its salts, when used as a substance in hair dye products",
            "N,N'-Dimethyl-N-Hydroxyethyl-3-nitro-p-phenylenediamine and its salts, when used as a substance in hair dye products",
            "3-(N-Methyl-N-(4-methylamino-3-nitrophenyl)amino)propane-1,2- diol and its salts, when used as a substance in hair dye products",
            "4-Ethylamino-3-nitrobenzoic acid (N-Ethyl-3-Nitro PABA) and its salts, when used as a substance in hair dye products",
            "(8-[(4-Amino-2-nitrophenyl)azo]-7-hydroxy-2 naphthyl)trimethylammonium and its salts, (except Basic Red 118 as impurity in Basic Brown 17) , when used as a substance in hair dye products",
            "5-((4-(Dimethylamino)phenyl)azo)-1,4-dimethyl-1H-1,2,4- triazolium and its salts, when used as a substance in hair dye products",
            "m-Phenylenediamine, 4-(phenylazo)- and its salts, when used as a substance in hair dye products",
            "1,3-Benzenediamine, 4-methyl-6-(phenylazo)- and its salts, when used as a substance in hair dye products",
            "2,7-Naphthalenedisulfonic acid, 5-(acetylamino)-4-hydroxy-3-((2- methylphenyl)azo)- and its salts, when used as a substance in hair dye products",
            "4,4'-[(4-Methyl-1,3-phenylene)bis(azo)]bis[6-methyl-1,3- benzenediamine] (Basic Brown 4) and its salts, when used as a substance in hair dye products",
            "Benzenaminium, 3-[[4-[[diamino(phenylazo)phenyl]azo]-2- methylphenyl]azo]-N,N,N-trimethyl- and its salts, when used as a substance in hair dye products",
            "Benzenaminium, 3-[[4-[[diamino(phenylazo)phenyl]azo]-1- naphthalenyl]azo]-N,N,N-trimethyl and its salts, when used as a substance in hair dye products",
            "Ethanaminium, N-(4-[(4-(diethylamino)phenyl)phenylmethylene]- 2,5-cyclohexadien-1-ylidene)-N-ethyl- and its salts, when used as a substance in hair dye products",
            "9,10-Anthracenedione, 1-[(2-hydroxyethyl)amino]-4- (methylamino)- and its derivatives and salts, when used as a substance in hair dye products",
            "1,4-Diamino-2-methoxy-9,10-anthracenedione (Disperse Red 11) and its salts, when used as a substance in hair dye products",
            "1,4-Dihydroxy-5,8-bis[(2-hydroxyethyl)amino]anthraquinone (Disperse Blue 7) and its salts, when used as a substance in hair dye products",
            "1-[(3-Aminopropyl)amino]-4-(methylamino)anthraquinone and its salts, when used as a substance in hair dye products",
            "N-[6-[(2-Chloro-4-hydroxyphenyl)imino]-4-methoxy-3-oxo-1,4- cyclohexadien-1-yl]acetamide (HC Yellow No 8) and its salts, when used as a substance in hair dye products",
            "[6-[[3-Chloro-4-(methylamino)phenyl]imino]-4-methyl-3- oxocyclohexa-1,4-dien-1-yl]urea (HC Red No 9) and its salts, when used as a substance in hair dye products",
            "Phenothiazin-5-ium, 3,7-bis(dimethylamino)- and its salts, when used as a substance in hair dye products",
            "4,6-Bis(2-hydroxyethoxy)-m-phenylenediamine and its salts, when used as a substance in hair dye products",
            "5-Amino-2,6-dimethoxy-3-hydroxypyridine and its salts, when used as a substance in hair dye products",
            "4,4'-Diaminodiphenylamine and its salts, when used as a substance in hair dye products",
            "4-Diethylamino-o-toluidine and its salts, when used as a substance in hair dye products",
            "N,N-Diethyl-p-phenylenediamine and its salts, when used as a substance in hair dye products",
            "N,N-Dimethyl-p-phenylenediamine and its salts, when used as a substance in hair dye products",
            "Toluene-3,4-diamine and its salts, when used as a substance in hair dye products",
            "2,4-Diamino-5-methylphenoxyethanol and its salts, when used as a substance in hair dye products",
            "6-Amino-o-cresol and its salts, when used as a substance in hair dye products",
            "Hydroxyethylaminomethyl-p-aminophenol and its salts, when used as a substance in hair dye products",
            "2-Amino-3-nitrophenol and its salts, when used as a substance in hair dye products",
            "2-Chloro-5-nitro-N-hydroxyethyl-p-phenylenediamine and its salts, when used as a substance in hair dye products",
            "2-Nitro-p-phenylenediamine and its salts, when used as a substance in hair dye products",
            "Hydroxyethyl-2,6-dinitro-p-anisidine and its salts, when used as a substance in hair dye products",
            "6-Nitro-2,5-pyridinediamine and its salts, when used as a substance in hair dye products",
            "Phenazinium, 3,7-diamino-2,8-dimethyl-5-phenyl- and its salts, when used as a substance in hair dye products",
            "3-Hydroxy-4-[(2-hydroxynaphthyl)azo]-7-nitronaphthalene-1- sulphonic acid and its salts, when used as a substance in hair dye products",
            "3-[(2-nitro-4-(trifluoromethyl)phenyl)amino]propane-1,2-diol  (HC Yellow No 6) and its salts, when used as a substance in hair dye products",
            "2-[(4-chloro-2-nitrophenyl)amino]ethanol (HC Yellow No 12) and its salts, when used as a substance in hair dye products",
            "3-[[4-[(2-Hydroxyethyl)Methylamino]-2-Nitrophenyl]amino]-1,2- propanediol and its salts, when used as a substance in hair dye products",
            "3-[[4-[(2-Hydroxyethyl)amino]-2-nitrophenyl]amino]-1,2- propanediol and its salts, when used as a substance in hair dye products",
            "Ethanaminium, N-[4-[[4-(diethylamino)phenyl][4-(ethylamino)-1- naphthalenyl]methylene]-2,5-cyclohexadien-1-ylidine]-N-ethyl- and its salts, when used as a substance in hair dye products",
            "4-[(4-Aminophenyl)(4-iminocyclohexa-2,5-dien-1- ylidene)methyl]-o-toluidine and its hydrochloride salt (Basic Violet 14; CI 42510) when used as a substance in hair dye products",
            "4-(2,4-Dihydroxyphenylazo)benzenesulphonic acid and its sodium salt (Acid Orange 6; CI 14270) when used as a substance in hair dye products",
            "3-Hydroxy-4-(phenylazo)-2-naphthoic acid and its calcium salt (Pigment Red 64:1; CI 15800) when used as a substance in hair dye products",
            "2-(6-Hydroxy-3-oxo-(3H)-xanthen-9-yl)benzoic acid; Fluorescein and its disodium salt (Acid Yellow 73 sodium salt; CI 45350), when used as a substance in hair dye products",
            "4',5'-Dibromo-3',6'-dihydroxyspiro[isobenzofuran-1(3H),9'- [9H]xanthene]-3-one; 4',5'-Dibromofluorescein; (Solvent Red 72) and its sodium salt (CI 45370) when used as a substance in hair dye products",
            "2-(3,6-Dihydroxy-2,4,5,7-tetrabromoxanthen-9-yl)benzoic acid; Fluorescein, 2',4',5',7'-tetrabromo-;(Solvent Red 43) and its disodium salt (Acid Red 87; CI 45380) and its aluminium salt (Pigment Red 90:1 Aluminium lake) when used as a substance in hair dye products",
            "Xanthylium, 9-(2-carboxyphenyl)-3-((2-methylphenyl)amino)-6- ((2-methyl-4-sulfophenyl)amino)-, inner salt and its sodium salt (Acid Violet 9; CI 45190)  when used as a substance in hair dye products",
            "3',6'-Dihydroxy-4',5'-diiodospiro(isobenzofuran-1(3H),9'- [9H]xanthene)-3-one; (Solvent Red 73) and its sodium salt (Acid Red 95; CI 45425)  when used as a substance in hair dye products",
            "2',4',5',7'-Tetraiodofluorescein , its disodium salt (Acid Red 51; CI 45430) and its aluminium salt (Pigment Red 172 Aluminium lake) when used as a substance in hair dye products",
            "1-Hydroxy-2,4-diaminobenzene (2,4-Diaminophenol) and its dihydrochloride salts (2,4-Diaminophenol HCl) when used as a substance in hair dye products",
            "1,4-Dihydroxybenzene (Hydroquinone), with the exception of entry 14 in Annex III",
            "[4-[[4-Anilino-1-naphthyl][4-dimethylamino)phenyl]methylene] cyclohexa-2,5-dien-1-ylidene]dimethylammonium chloride",
            "(Basic Blue 26; CI 44045) when used as a substance in hair dye products",
            "Disodium 3-[(2,4-dimethyl-5-sulphonatophenyl)azo]-4- hydroxynaphthalene-1-sulphonate (Ponceau SX; CI 14700) when used as a substance in hair dye products",
            "Trisodium tris[5,6-dihydro-5-(hydroxyimino)-6-oxonaphthalene- 2-sulphonate(2-)-N5,O6]ferrate(3-); (Acid Green 1; CI 10020) when used as a substance in hair dye products",
            "4-(Phenylazo)resorcinol (Solvent Orange 1; CI 11920) and its salts, when used as a substance in hair dye products",
            "4-[(4-Ethoxyphenyl)azo]naphthol (Solvent Red 3; CI 12010) and its salts, when used as a substance in hair dye products",
            "1-[(2-Chloro-4-nitrophenyl)azo]-2-naphthol (Pigment Red 4; CI 12085) and its salts when used as a substance in hair dye products",
            "3-Hydroxy-N-(o-tolyl)-4-[(2,4,5-trichlorophenyl)azo]naphthalene- 2-carboxamide (Pigment Red 112; CI12370) and its salts when used as a substance in hair dye products",
            "N-(5-Chloro-2,4-dimethoxyphenyl)-4-[[5- [(diethylamino)sulphonyl]-2-methoxyphenyl]azo]-3- hydroxynaphthalene-2-carboxamide (Pigment Red 5; CI 12490) and its salts when used as a substance in hair dye products",
            "Disodium 4-[(5-chloro-4-methyl-2-sulphonatophenyl)azo]-3- hydroxy-2-naphthoate (Pigment Red 48; CI 15865) when used as a substance in hair dye products",
            "Calcium 3-hydroxy-4-[(1-sulphonato-2-naphthyl)azo]-2- naphthoate Pigment Red 63:1; CI 15880) when used as a substance in hair dye products",
            "Trisodium 3-hydroxy-4-(4'-sulphonatonaphthylazo)naphthalene- 2,7-disulphonate (Acid Red 27; CI 16185) when used as a substance in hair dye products",
            "2,2'-[(3,3'-Dichloro[1,1'-biphenyl]-4,4'-diyl)bis(azo)bis[N-(2,4- dimethylphenyl)-3-oxobutyramide] (Pigment Yellow 13; CI 21100) when used as a substance in hair dye products",
            "2,2'-[Cyclohexylidenebis[(2-methyl-4,1-phenylene)azo]]bis[4- cyclohexylphenol] (Solvent Yellow 29; CI 21230) when used as a substance in hair dye products",
            "1-((4-Phenylazo)phenylazo)-2-naphthol (Solvent Red 23; CI 26100) when used as a substance in hair dye products",
            "Tetrasodium 6-amino-4-hydroxy-3-[[7-sulphonato-4-[(4- sulphonatophenyl)azo]-1-naphthyl]azo]naphthalene-2,7- disulphonate (Food Black 2; CI 27755) when used as a substance in hair dye products",
            "Ethanaminium, N-(4-((4-diethylamino)phenyl)(2,4- disulfophenyl)methylene)-2,5-cyclohexadien-1-ylidene)-N-ethyl-, hydroxide, inner salt, sodium salt (Acid Blue 1; CI 42045) when used as a substance in hair dye products",
            "Ethanaminium, N-(4-((4-diethylamino)phenyl)(5-hydroxy-2,4- disulphophenyl)methylene)-2,5-cyclohexadien-1-ylidene)-N- ethyl-, hydroxide, inner salt, calcium salt (2:1) (Acid Blue 3; CI 42051) when used as a substance in hair dye products",
            "Benzenemethanaminium, N-ethyl-N-(4-((4-(ethyl((3- sulfophenyl)methyl)amino)phenyl)(4-hydroxy-2- sulfophenyl)methylene)-2,5-cyclohexadien-1-ylidene)-3-sulfo-, hydroxide, inner salt, disodium salt (Fast Green FCF; CI 42053) when used as a substance in hair dye products",
            "1,3-Isobenzofurandione, reaction products with methylquinoline and quinoline (Solvent Yellow 33; CI 47000) when used as a substance in hair dye products",
            "Nigrosine (CI 50420) when used as a substance in hair dye products",
            "8,18-Dichloro-5,15-diethyl-5,15-dihydrodiindolo[3,2-b:3',2'- m]triphenodioxazine (Pigment Violet 23; CI 51319) when used as a substance in hair dye products",
            "1,2-Dihydroxyanthraquinone (Pigment Red 83; CI 58000) when used as a substance in hair dye products",
            "Trisodium 8-hydroxypyrene-1,3,6-trisulphonate (Solvent Green 7; CI 59040) when used as a substance in hair dye products",
            "1-Hydroxy-4-(p-toluidino)anthraquinone (Solvent Violet 13; CI 60725) when used as a substance in hair dye products",
            "1,4-bis(p-Tolylamino)anthraquinone (Solvent Green 3; CI 61565) when used as a substance in hair dye products",
            "6-Chloro-2-(6-chloro-4-methyl-3-oxobenzo[b]thien-2(3H)- ylidene)-4-methylbenzo[b]thiophene-3(2H)-one (VAT Red 1; CI 73360) when used as a substance in hair dye products",
            "5,12-Dihydroquino[2,3-b]acridine-7,14-dione (Pigment Violet 19; CI 73900) when used as a substance in hair dye products",
            "(29H,31H-Phthalocyaninato(2-)-N29,N30,N31,N32)copper (Pigment Blue 15; CI 74160) when used as a substance in hair dye products",
            "Disodium [29H,31H-phthalocyaninedisulphonato(4-)- N29,N30,N31,N32]cuprate(2-) (Direct Blue 86; CI 74180) when used as a substance in hair dye products",
            "Polychloro copper phthalocyanine (Pigment Green 7; CI 74260) when used as a substance in hair dye products",
            "Entry deleted",
            "Phytonadione (INCI), phytomenadione (INN)",
            "2-Aminophenol (o-Aminophenol; CI 76520) and its salts",
            "N-(2-Nitro-4-aminophenyl)-allylamine (HC Red No 16) and its salts",
            "Exception for Indonesia: include under Annex VI",
            "Isobutyl 4-hydroxybenzoate (INCI: Isobutylparaben)",
            "Sodium salt or Salts of Isobutylparaben Exception for Indonesia: include under Annex VI",
            "Phenyl 4-hydroxybenzoate (INCI: Phenylparaben)",
            "Benzyl 4-hydroxybenzoate (INCI: Benzylparaben) Exception for Indonesia: include under Annex VI",
            "Pentyl 4-hydroxybenzoate (INCI: Pentylparaben)",
            "3-Benzylidene camphor (3-Benzylidene Camphor)",
            "3- and 4-(4-Hydroxy-4-methylpentyl) cyclohex-3-ene-1- carbaldehyde (HICC)",
            "2,6-Dihydroxy-4-methyl-benzaldehyde (atranol)",
            "3-Chloro-2,6-Dihydroxy-4-methyl-benzaldehyde (chloroatranol)",
            "2-chlorobenzene-1,4-diamine (2-Chloro-p-Phenylenediamine), its sulfate and dihydrochloride salts when used as a substance in hair dye products",
            "Cis-1-(3-chloroallyl)-3,5,7- triaza-1-azoniaadamantane chloride (cis-CTAC)",
            "2,2’-((3,3’,5,5’-Tetramethyl-(1,1’-biphenyl)-4,4’-diyl)- bis(oxymethylene))-bis-oxirane",
            "1-Cyclopropyl-6,7-difluoro-1,4-dihydro-4-oxoquinoline-3- carboxylic acid",
            "Diboron trioxide; boric oxide",
            "Dibutyltin hydrogen borate",
            "Nickel bis(tetrafluoroborate)",
            "Mancozeb (ISO); manganese ethylenebis(dithiocarbamate) (polymeric) complex with zinc salt",
            "Maneb (ISO); manganese ethylenebis(dithiocarbamate) (polymeric)",
            "Benfuracarb (ISO); ethyl N-[2,3-dihydro-2,2- dimethylbenzofuran-7-yloxycarbonyl(methyl)65minothiol]-N- isopropyl- ß-alaninate",
            "O-Isobutyl-N-ethoxy carbonylthiocarbamate",
            "Chlorpropham (ISO); isopropyl 3-chlorocarbanilate",
            "O-Hexyl-N-ethoxycarbonylthiocarbamate",
            "1Hydroxylammonium nitrate",
            "(4-Ethoxyphenyl)(3-(4-fluoro-3- phenoxyphenyl)propyl)dimethylsilane",
            "Phoxim (ISO); a-(diethoxy-phosphinothioylimino) phenylacetonitrile",
            "Glufosinate ammonium (ISO); ammonium 2-amino-4- (hydroxymethylphosphinyl)butyrate",
            "Potassium titanium oxide (K2Ti6O13)",
            "Cobalt di(acetate)",
            "Cobalt dinitrate",
            "Cobalt carbonate",
            "Nickel dichloride",
            "Nickel dinitrate [1]; Nitric acid, nickel salt [2]",
            "Nickel matte",
            "Slimes and sludges, copper electrolytic refining, decopperised, nickel sulfate",
            "Slimes and sludges, copper electrolyte refining, decopperised",
            "Nickel diperchlorate; perchloric acid, nickel(II) salt",
            "Nickel dipotassium bis(sulfate) [1]; Diammonium nickel bis(sulfate) [2] 13842-46",
            "Nickel bis(sulfamidate); nickel sulfamate",
            "Nickel di(acetate) [1]; Nickel acetate [2] 373-02",
            "Nickel dibenzoate",
            "Nickel bis(4-cyclohexylbutyrate)",
            "Nickel(II) stearate; nickel(II) octadecanoate",
            "Nickel dilactate",
            "Nickel(II) octanoate",
            "Nickel difluoride [1]; Nickel dibromide [2]; Nickel diiodide [3]; Nickel potassium fluoride [4]",
            "Nickel hexafluorosilicate",
            "Nickel selenate",
            "Diammonium nickel hexacyanoferrate",
            "Nickel dicyanide",
            "Nickel chromate",
            "hydroxybis[orthosilicato(4-)]trinickelate(3-) [5]",
            "Dinickel hexacyanoferrate",
            "Trinickel bis(arsenate); nickel(II) arsenate",
            "Nickel oxalate [1]; Oxalic acid, nickel salt [2]",
            "Nickel telluride",
            "Trinickel tetrasulfide",
            "Trinickel bis(arsenite)",
            "Cobalt nickel gray periclase; C.I. Pigment Black 25; C.I. 77332 [1]; Cobalt nickel dioxide [2]; Cobalt nickel oxide [3]; Nickel arsenide [2]",
            "Nickel tin trioxide; nickel stannate",
            "Nickel triuranium decaoxide",
            "Nickel dithiocyanate",
            "Nickel dichromate",
            "Nickel(II) selenite",
            "Nickel selenide",
            "Silicic acid, lead nickel salt",
            "Cobalt lithium nickel oxide",
            "Molybdenum trioxide",
            "Dibutyltin dichloride; (DBTC) 683-18",
            "4,4'-Bis(N-carbamoyl-4- methylbenzenesulfonamide)diphenylmethane",
            "Furfuryl alcohol",
            "1,2-Epoxy-4-epoxyethylcyclohexane; 4-vinylcyclohexene diepoxide",
            "6-Glycidyloxynapht-1-yl oxymethyloxirane",
            "2-(2-Aminoethylamino)ethanol; (AEEA)",
            "1,2-Diethoxyethane",
            "2,3-Epoxypropyltrimethylammonium chloride; glycidyl trimethylammonium chloride",
            "1-(2-Amino-5-chlorophenyl)-2,2,2-trifluoro-1,1-ethanediol, hydrochloride",
            "(E)-3-[1-[4-[2-(Dimethylamino)ethoxy]phenyl]-2-phenylbut-1- enyl]phenol",
            "4,4'-(1,3-Phenylene-bis(1-methylethylidene))bis-phenol",
            "2-Chloro-6-fluoro-phenol",
            "2-Methyl-5-tert-butylthiophenol",
            "2-Butyryl-3-hydroxy-5-thiocyclohexan-3-yl-cyclohex-2-en-1-one",
            "chlorophenoxy)propoxyimino]butyl}-3-hydroxy-5-(thian-3- yl)cyclohex-2-en-1-one",
            "chloroallyloxyimino]propyl}-3-hydroxy-5-perhydropyran-4- ylcyclohex-2-en-1-one",
            "Cyclic 3-(1,2-ethanediylacetale)-estra-5(10),9(11)-diene-3,17- dione",
            "Androsta-1,4,9(11)-triene-3,17-dione",
            "Reaction mass of: Ca salicylates (branched C10-14 and C18-30 alkylated); Ca phenates (branched C10-14 and C18-30 alkylated); Ca sulfurised phenates (branched C10-14 and C18- 30 alkylated)",
            "1,2-Benzenedicarboxylic acid; di-C6-8-branched alkylesters, C7-rich",
            "Reaction mass of: diester of 4,4'-methylenebis[2-(2-hydroxy-5- methylbenzyl)-3,6-dimethylphenol] and 6-diazo-5,6-dihydro-5- oxonaphthalene-1-sulfonic acid (1:2); triester of 4,4'- methylenebis[2-(2-hydroxy-5-methylbenzyl)-3,6- dimethylphenol] and 6-diazo-5,6-dihydro-5-oxonaphthalene-1- sulfonic acid (1:3)",
            "Diammonium 1-hydroxy-2-(4-(4-carboxyphenylazo)-2,5- dimethoxyphenylazo)-7-amino-3-naphthalenesulfonate",
            "3-Oxoandrost-4-ene-17-ß-carboxylic acid",
            "(Z)-2-Methoxymino-2-[2-(tritylamino)thiazol-4-yl]acetic acid",
            "Diisobutyl phthalate",
            "Perfluorooctane sulfonic acid; heptadecafluorooctane-1- sulfonic acid [1]; Potassium perfluorooctanesulfonate; potassium heptadecafluorooctane-1-sulfonate [2]; Diethanolamine perfluorooctane sulfonate [3]; Ammonium perfluorooctane sulfonate; ammonium heptadecafluorooctanesulfonate [4]; Lithium perfluorooctane sulfonate; lithium heptadecafluorooctanesulfonate [5]",
            "Ethyl 1-(2,4-dichlorophenyl)5-(trichloromethyl)-1H-1,2,4- triazole-3-carboxylate",
            "1-Bromo-2-methylpropyl propionate",
            "Chloro-1-ethylcyclohexyl carbonate",
            "6,6'-Bis(diazo-5,5',6,6'-tetrahydro-5,5'-dioxo)[methylene-bis(5- (6-diazo-5,6-dihydro-5-oxo-1-naphthylsulphonyloxy)-6-methyl- 2-phenylene]di(naphthalene-1-sulfonate)",
            "Trifluralin (ISO); a,a,a-trifluoro-2,6-dinitro-N,N-dipropyl-p- toluidine; 2,6-dinitro-N,N-dipropyl-4-trifluoromethylaniline; N,N- dipropyl-2,6-dinitro-4-trifluoromethylaniline",
            "4-Mesyl-2-nitrotoluene",
            "Triammonium 4-[4-[7-(4-carboxylatoanilino)-1-hydroxy-3- sulfonato-2-naphthylazo]-2,5-dimethoxyphenylazo]benzoate",
            "Reaction mass of: triammonium 6-amino-3-((2,5-diethoxy-4-(3- phosphonophenyl)azo)phenyl)azo-4-hydroxy-2- naphthalenesulfonate; diammonium 3-((4-((7-amino-1-hydroxy- 3-sulfo-naphthalen-2-yl)azo)-2,5-diethoxyphenyl)azo)benzoate",
            "N,N'-Diacetylbenzidine",
            "Piperazine",
            "Hydroxylamine",
            "Hydroxylammonium chloride; hydroxylamine hydrochloride [1]; Bis(hydroxylammonium) sulfate; hydroxylamine sulfate (2:1) [2]",
            "Mepanipyrim; 4-methyl-N-phenyl-6-(1-propynyl)-2- pyrimidinamine",
            "dihydrogenphosphate [3]; Hydroxylamine 4-",
            "methylbenzenesulfonate [4]",
            "(3-Chloro-2-hydroxypropyl) trimethylammonium chloride",
            "Biphenyl-3,3',4,4'-tetrayltetraamine; diaminobenzidine",
            "Piperazine phosphate [3]",
            "3-(Piperazin-1-yl)-benzo[d]isothiazole hydrochloride",
            "2-Ethylphenylhydrazine hydrochloride",
            "(2-Chloroethyl)(3-hydroxypropyl)ammonium chloride",
            "4-[(3-Chlorophenyl)(1H-imidazol-1-yl)methyl]-1,2- benzenediamine dihydrochloride",
            "Chloro-N,N-dimethylformiminium chloride",
            "7-Methoxy-6-(3-morpholin-4-yl-propoxy)-3H-quinazolin-4-one",
            "Reaction products of diisopropanolamine with formaldehyde (1:4)",
            "3-Chloro-4-(3-fluorobenzyloxy)aniline",
            "Ethidium bromide; 3,8-diamino-1-ethyl-6- phenylphenantridinium bromide",
            "(R,S)-2-Amino-3,3-dimethylbutane amide",
            "3-Amino-9-ethyl carbazole; 9-ethylcarbazol-3-ylamine",
            "(6R-trans)-1-((7-Ammonio-2-carboxylato-8-oxo-5-thia-1- azabicyclo-[4.2.0]oct-2-en-3-yl)methyl)pyridinium iodide",
            "Forchlorfenuron (ISO); 1-(2-chloro-4-pyridyl)-3-phenylurea",
            "Tetrahydro-1,3-dimethyl-1H-pyrimidin-2-one; dimethyl propyleneurea",
            "Ketoconazole; 1-[4-[4-[[(2SR,4RS)-2-(2,4-dichlorophenyl)-2- (imidazol-1-ylmethyl)-1,3-dioxolan-4- yl]methoxy]phenyl]piperazin-1-yl]ethanone",
            "Metconazole (ISO); (1RS,5RS;1RS,5SR)-5-(4-chlorobenzyl)-2,2- dimethyl-1-(1H-1,2,4-triazol-1-ylmethyl)cyclopentanol",
            "Potassium 1-methyl-3-morpholinocarbonyl-4-[3-(1-methyl-3- morpholinocarbonyl-5-oxo-2-pyrazolin-4-ylidene)-1- propenyl]pyrazole-5-olate",
            "N,N',N''-Tris(2-methyl-2,3-epoxypropyl)-perhydro-2,4,6-oxo- 1,3,5-triazine",
            "Trimethylopropane tri(3-aziridinylpropanoate); (TAZ)",
            "4,4'-Methylenediphenyl diisocyanate; diphenylmethane-4,4'- diisocyanate [1]; 2,2'-Methylenediphenyl diisocyanate; diphenylmethane-2,2'-diisocyanate [2]; o-(p- Isocyanatobenzyl)phenyl isocyanate; diphenylmethane-2,4'- diisocyanate [3]; Methylenediphenyl diisocyanate [4]",
            "Cinidon ethyl (ISO); ethyl (Z)-2-chloro-3-[2-chloro-5-(cyclohex- 1-ene-1,2-dicarboximido)phenyl]acrylate",
            "N-[6,9-Dihydro-9-[[2-hydroxy-1-(hydroxymethyl)ethoxy]methyl]- 6-oxo-1H-purin-2-yl]acetamide",
            "Dimoxystrobin (ISO); (E)-2-(methoxyimino)-N-methyl-2-[a-(2,5- xylyloxy)-o-tolyl]acetamide",
            "N,N-(Dimethylamino)thioacetamide hydrochloride",
            "Reaction mass of: 2,2'-[(3,3'-dichloro[1,1'-biphenyl]-4,4'- diyl)bis(azo)]bis[N-(2,4-dimethylphenyl)]-3-oxo-butanamide; 2- [[3,3'-dichloro-4'-[[1[[(2,4-dimethylphenyl)amino]carbonyl]-2- oxopropyl]azo][1,1'-biphenyl]-4-yl]azo]-N-(2-methylphenyl)-3- oxo-butanamide; 2-[[3,3'-dichloro-4'-[[1[[(2,4- dimethylphenyl)amino]carbonyl]-2-oxopropyl]azo][1,1'- biphenyl]-4-yl]azo]-N-(2-carboxylphenyl)-3- oxo-butanamide",
            "Petroleum, coal, tar and natural gas and their derivatives generated using distillation and/or other processing methods if they contain = 0,005 % w/w benzo[a]pyrene",
            "Petroleum, coal, tar and natural gas and their derivatives generated using distillation and/or other processing methods if they contain = 0,1 % w/w benzene or if they contain = 0,005 % w/w benzo[a]pyrene",
            "Tris[2-chloro-1-(chloromethyl)ethyl] phosphate",
            "Indium phosphide",
            "Trixylyl phosphate",
            "Hexabromocyclododecane [1]; 1,2,5,6,9,10-",
            "Hexabromocyclododecane [2]",
            "Tetrahydrofuran",
            "Abamectin (combination of avermectin B1a and avermectin B1b) (ISO) [1]; Avermectin B1a [2]",
            "4-tert-Butylbenzoic acid",
            "Leucomalachite green; N,N,N',N'-tetramethyl-4,4'- benzylidenedianiline",
            "Fuberidazole (ISO); 2-(2-furyl)-1H-benzimidazole",
            "Metazachlor (ISO); 2-chloro-N-(2,6-dimethylphenyl)-N-(1H- pyrazol-1-ylmethyl)acetamide 67129-08",
            "Di-tert-butyl peroxide",
            "Trichloromethylstannane",
            "2-Ethylhexyl 10-ethyl-4-[[2-[(2-ethylhexyl)oxy]-2-oxoethyl]thio]- 4-methyl-7-oxo-8-oxa-3,5-dithia-4-stannatetradecanoate",
            "2-Ethylhexyl 10-ethyl-4,4-dioctyl-7-oxo-8-oxa-3,5-dithia-4- stannatetradecanoate",
            "Sulcotrione (ISO); 2-[2-chloro-4- (methylsulfonyl)benzoyl]cyclohexane-1,3-dione",
            "Bifenthrin (ISO); (2-methylbiphenyl-3-yl)methyl rel-(1R,3R)-3- [(1Z)-2-chloro-3,3,3-trifluoroprop-1-en-1-yl]-2,2- dimethylcyclopropanecarboxylate",
            "Dihexyl phthalate",
            "Ammonium pentadecafluorooctanoate",
            "Perfluorooctanoic acid",
            "Proquinazid (ISO); 6-iodo-2-propoxy-3-propylquinazolin-4(3H)- one",
            "Gallium arsenide",
            "Aclonifen (ISO); 2-chloro-6-nitro-3-phenoxyaniline",
            "2-Ethylhexyl 10-ethyl-4,4-dimethyl-7-oxo-8-oxa-3,5-dithia-4- stannatetradecanoate",
            "Dimethyltin dichloride",
            "4-Vinylcyclohexene",
            "Tralkoxydim (ISO); 2-(N-ethoxypropanimidoyl)-3-hydroxy-5- mesitylcyclohex-2-en-1-one",
            "Cycloxydim (ISO); 2-(N-ethoxybutanimidoyl)-3-hydroxy-5- (tetrahydro-2H-thiopyran-3-yl)cyclohex-2-en-1-one",
            "Fluazinam (ISO); 3-chloro-N-[3-chloro-2,6-dinitro-4- (trifluoromethyl)phenyl]-5-(trifluoromethyl)pyridin-2-amine",
            "Penconazole (ISO); 1-[2-(2,4-dichlorophenyl)pentyl]-1H-1,2,4- triazole",
            "Fenoxycarb (ISO); ethyl [2-(4- phenoxyphenoxy)ethyl]carbamate",
            "Formaldehyde Except Lao PDR",
            "Paraformaldehyde",
            "Methanediol: methylene glycol",
            "Cymoxanil (ISO); 2-cyano-N-[(ethylamino)carbonyl]-2- (methoxyimino)acetamide",
            "Tributyltin compounds",
            "Tembotrione (ISO); 2-{2-chloro-4-(methylsulfonyl)-3-[(2,2,2- trifluoroethoxy)methyl]benzoyl}cyclohexane-1,3-dione",
            "1,2-Benzenedicarboxylic acid, dihexyl ester, branched and linear",
            "Spirotetramat (ISO); (5s,8s)-3-(2,5-dimethylphenyl)-8-methoxy- 2-oxo-1-azaspiro[4,5]dec-3-en-4-yl ethyl carbonate",
            "Dodemorph acetate; 4-cyclododecyl-2,6-dimethylmorpholin-4- ium acetate",
            "Triflusulfuron-methyl; methyl 2-({[4-(dimethylamino)-6-(2,2,2- trifluoroethoxy)-1,3,5-triazin-2- yl]carbamoyl}sulfamoyl)-3- methylbenzoate",
            "Imazalil (ISO); 1-[2-(allyloxy)-2-(2,4-dichlorophenyl)ethyl]-1H- imidazole",
            "Dodemorph (ISO); 4-cyclododecyl-2,6-dimethylmorpholine",
            "Lenacil (ISO); 3-cyclohexyl-6,7-dihydro-1H- cyclopenta[d]pyrimidine-2,4(3H,5H)-dione",
            "Metosulam (ISO); N-(2,6-dichloro-3-methylphenyl)-5,7- dimethoxy[1,2,4]triazolo[1,5-a]pyrimidine-2-sulfonamide",
            "2-Methyl-1-(4-methylthiophenyl)-2-morpholino-propan 1-one",
            "2,3-Epoxypropyl methacrylate; glycidyl methacrylate",
            "Spiroxamine (ISO); 8-tert-butyl-1,4-dioxaspirol[4.5]decan-2- ylmethyl(ethyl)(propyl)amine",
            "Cyanamide; carbanonitril",
            "Cyproconazole (ISO); (2RS,3RS;2RS,3SR)-2-(4-chlorophenyl)-3- cyclopropyl-1-(1H-1,2,4-triazol-1-yl)butan-2-ol",
            "Cadmium carbonate",
            "Cadmium hydroxide; cadmium dihydroxide",
            "Cadmium nitrate; cadmium dinitrate",
            "Dibutyltin dilaurate; dibutyl[bis(dodecanoyloxy)] stannane",
            "9,10-anthraquinone Anthraquinone",
            "nonadecafluorodecanoate [3]",
            "N,N'-Methylenedimorpholine; N,N'-methylenebismorpholine; [formaldehyde released from N,N'-Methylenebismorpholine]; [MBM] if the maximum theoretical concentration of releasable formaldehyde, irrespective of the source, in the mixture as placed on the market is = 0,1 % w/w",
            "Reaction products of paraformaldehyde with 2- hydroxypropylamine (3:2); [formaldehyde released from 3,3'- methylenebis[5–methyloxazolidine]; [formaldehyde released from oxazolidin]; [MBO] if the maximum theoretical concentration of releasable formaldehyde, irrespective of the source, in the mixture as placed on the market is = 0,1 % w/w",
            "Reaction products of paraformaldehyde with 2- hydroxypropylamine (1:1)); [formaldehyde released from a,a,a- trimethyl-1,3,5-triazine-1,3,5(2H,4H,6H)-triethanol]; [HPT] if the maximum theoretical concentration of releasable formaldehyde, irrespective of the source, in the mixture as placed on the market is = 0,1 % w/w",
            "Methylhydrazine",
            "Triadimenol (ISO); (1RS,2RS;1RS,2SR)-1-(4-chlorophenoxy)- 3,3-dimethyl-1-(1H-1,2,4-triazol-1-yl)butan-2-ol; a-tert-butyl-ß-(4- chlorophenoxy)-1H-1,2,4-triazole-1-ethanol",
            "Thiacloprid (ISO); (Z)-3-(6-chloro-3-pyridyl-methyl)-1-3- thiazolidin-2-ylidenecyanamide; {(2Z)-3-[(6-chloropyridin-3- yl)methyl]-1,3-thiazolidin-2-ylidene}cyanamide",
            "Carbetamide (ISO); (R)-1-(ethylcarbamoyl) ethyl-carbanilate; (2R)-1-(ethylamino) -1-oxopro-pan-2-yl-phenylcarbamate",
            "Phosmet (ISO); S-[(1,3-dioxo-1,3-dihydro-2H- isoindol-2- yl)methyl]-O,O-dimethyl phosphorodithioate; O,O-dimethyl-S- phthalimidomethyl phosphorodithioate",
            "Potassium permanganate",
            "2-Benzyl-2-dimethylamino-4'- morpholinobutyrophenone",
            "Quizalofop-p-tefuryl (ISO); (+/–) tetrahydrofurfuryl (R)-2-[4-(6- chloroquinoxalin-2-yloxy)phenyloxy]propionate",
            "dichlorophenyl)-4-propyl-1,3- dioxolan-2-yl]methyl}-1H- 1,2,4- triazole",
            "Pinoxaden (ISO); 8-(2,6-diethyl-4-methylphenyl)-7-oxo-1,2,4,5- tetrahydro-7H-pyrazolo[1,2-d][1,4,5]oxadiazepin-9-yl 2,2- dimethylpropanoate",
            "Tetramethrin; (1-Cyclohexene-1,2-Dicarboximido)Methyl Chrysanthemate; 2,2-Dimethyl-3-(2-Methyl-1- Propenyl)Cyclopropanecarboxylic Acid (1,3,4,5,6,7-Hexahydro- 1,3-Dioxo-2H-Isoindol-2-yl)Methyl Ester",
            "(1,3,4,5,6,7-Hexahydro-1,3-dioxo-2H-isoindol-2-yl)methyl (1R- trans)-2,2-dimethyl-3-(2- methylprop-1- enyl)cyclopropanecarboxylate",
            "Spirodiclofen (ISO); 3-(2,4-dichlorophenyl)-2-oxo- 1- oxaspiro[4.5]dec-3-en-4-yl 2,2-dimethylbutyrate",
            "Reaction mass of 1-[2-(2-aminobutoxy)ethoxy]but-2-ylamine and 1-({[2-(2-aminobutoxy)ethoxy]methyl}propoxy) but-2- ylamine",
            "1-Vinylimidazole",
            "Amisulbrom (ISO)3-(3-bromo-6-fluoro-2-methylindol-1- ylsulfonyl)-N,N-dimethyl-1H-1,2,4-triazole-1-sulfonamide",
            "Pirimicarb (ISO); 2-(dimethylamino)-5,6-dimethylpyrimidin-4-yl dimethylcarbamate",
            "1,2-Dichloropropane; propylene dichloride",
            "Phenol, dodecyl-, branched [1] Phenol, 2-dodecyl-, branched [2] Phenol, 3-dodecyl-, branched [3] Phenol, 4-dodecyl-, branched [4] Phenol, (tetrapropenyl) derivatives [5]",
            "Coumatetralyl (ISO); 4- hydroxy-3-(1,2,3,4-tetrahydro-1- naphthyl) coumarin",
            "Difenacoum (ISO); 3-(3- biphenyl-4-yl-1,2,3,4- tetrahydro- 1- naphthyl)- 4-hydroxycoumarin",
            "Brodifacoum (ISO); 4-hydroxy-3-(3-(4′-bromo-4-biphenylyl)- 1,2,3,4-tetrahydro-1-naphthyl)coumarin",
            "Flocoumafen (ISO); reaction mass of: cis-4- hydroxy-3- (1,2,3,4- tetrahydro-3-(4-(4-trifluoromethylbenzyloxy)phenyl)-1- naphthyl)coumarin and trans-4-hydroxy-3-(1,2,3,4- tetrahydro- 3-(4-(4-trifluoromethylbenzyloxy)phenyl)-1- naphthyl)coumarin",
            "Acetochlor (ISO); 2- chloro-N-(ethoxymethyl)-N-(2-ethyl-6- methylphenyl)acetamide",
            "e-Glass microfibres of representative composition",
            "Glass microfibres of representative composition",
            "Bromadiolone (ISO); 3- [3-(4′-bromobiphenyl- 4-yl)-3-hydroxy- 1-phenylpropyl]-4-hydroxy- 2H-chromen-2-one",
            "Difethialone (ISO); 3-[3-(4′-bromobiphenyl-4-yl)-1,2,3,4- tetrahydronaphthalen-1-yl]- 4-hydroxy-2H-1-benzothiopyran-2- one",
            "Perfluorononan-1-oic acid [1] and its sodium [2] and ammonium [3] salts",
            "Dicyclohexyl phthalate",
            "3,7-Dimethylocta-2,6- dienenitrile",
            "Bupirimate (ISO); 5-butyl-2-ethylamino-6- methylpyrimidin-4-yl dimethylsulfamate",
            "Triflumizole (ISO); (1E)-N-[4-chloro-2-(trifluoromethyl) phenyl]- 1- (1H-imidazol-1-yl)-2- propoxyethanimine",
            "tert-Butyl hydroperoxide",
            "1,2,4-Trihydroxybenzene when used as a substance in hair and eyelash dye products",
            "4-Amino-3-hydroxytoluene when used as a substance in hair and eyelash dye products",
            "2-[(4-Amino-2-nitrophenyl)-amino]-benzoic acid when used as a substance in hair and eyelash dye products"
    };
}